/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-07-16 11:09:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class all_002dproducts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Tất cả sản phẩm - 43 Gundam Hobby</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/layout-sizing.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/category-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-darkmode.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-bg-orange.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-menu-white.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/hamburger-menu.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-fix.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/account-menu-fix.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/user-avatar.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"bg-white shadow-sm sticky-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center py-3\">\r\n");
      out.write("                <!-- Logo Section with Hamburger Menu -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6\">\r\n");
      out.write("                    <div class=\"header-logo-section\">\r\n");
      out.write("                        <!-- Hamburger Menu (Mobile) -->\r\n");
      out.write("                        <button class=\"hamburger-menu\" id=\"hamburgerBtn\" aria-label=\"Menu\">\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"logo\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" alt=\"43 Gundam Logo\" class=\"logo-img\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Search Section -->\r\n");
      out.write("                <div class=\"col-lg-6 col-md-4 col-12 order-lg-2 order-md-2 order-3\">\r\n");
      out.write("                    <div class=\"header-center-section\">\r\n");
      out.write("                        <div class=\"search-container w-100\">\r\n");
      out.write("                            <form class=\"search-form\" action=\"");
      out.print(request.getContextPath());
      out.write("/search.jsp\" method=\"get\" id=\"headerSearchForm\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"q\" class=\"form-control search-input\" \r\n");
      out.write("                                           placeholder=\"Tìm kiếm sản phẩm...\" id=\"headerSearchInput\" autocomplete=\"off\">\r\n");
      out.write("                                    <button class=\"btn btn-search\" type=\"submit\">\r\n");
      out.write("                                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Autocomplete suggestions -->\r\n");
      out.write("                                <div id=\"headerSearchSuggestions\" class=\"search-suggestions\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Actions Section -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 order-lg-3 order-md-3 order-2\">\r\n");
      out.write("                    <div class=\"header-actions-section\">\r\n");
      out.write("                        <div class=\"account-menu me-3\">\r\n");
      out.write("                            <!-- User Info (visible when logged in) -->\r\n");
      out.write("                            <div id=\"nav-user-info\" class=\"d-none\">\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-outline-success dropdown-toggle d-flex align-items-center\" \r\n");
      out.write("                                       id=\"userAccountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                        <div class=\"user-avatar-container me-2\">\r\n");
      out.write("                                            <img id=\"userAvatarImage\" \r\n");
      out.write("                                                 src=\"");
      out.print(request.getContextPath());
      out.write("/img/placeholder.jpg\" \r\n");
      out.write("                                                 alt=\"User Avatar\" \r\n");
      out.write("                                                 class=\"user-avatar rounded-circle\"\r\n");
      out.write("                                                 style=\"width: 32px; height: 32px; object-fit: cover;\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"d-none d-md-inline\">\r\n");
      out.write("                                            <span class=\"greeting-text\">Xin chào</span>\r\n");
      out.write("                                            <span id=\"userDisplayName\" class=\"fw-bold\">User</span>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"d-md-none\">\r\n");
      out.write("                                            <span id=\"userDisplayNameMobile\" class=\"fw-bold\">User</span>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                                        <li><h6 class=\"dropdown-header d-flex align-items-center\">\r\n");
      out.write("                                            <img id=\"userAvatarDropdown\" \r\n");
      out.write("                                                 src=\"");
      out.print(request.getContextPath());
      out.write("/img/placeholder.jpg\" \r\n");
      out.write("                                                 alt=\"User Avatar\" \r\n");
      out.write("                                                 class=\"user-avatar-small rounded-circle me-2\"\r\n");
      out.write("                                                 style=\"width: 24px; height: 24px; object-fit: cover;\">\r\n");
      out.write("                                            <span id=\"userFullName\">User Name</span>\r\n");
      out.write("                                        </h6></li>\r\n");
      out.write("                                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/profile.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-user-edit me-2\"></i>Thông tin tài khoản\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                            <i class=\"fas fa-shopping-bag me-2\"></i>Đơn hàng của tôi\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">\r\n");
      out.write("                                            <i class=\"fas fa-heart me-2\"></i>Sản phẩm yêu thích\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item text-danger\" href=\"#\" onclick=\"userLogout()\">\r\n");
      out.write("                                            <i class=\"fas fa-sign-out-alt me-2\"></i>Đăng xuất\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- Login Button (visible when not logged in) -->\r\n");
      out.write("                            <div id=\"nav-login-btn\">\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-outline-primary dropdown-toggle\" \r\n");
      out.write("                                       id=\"accountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                        <i class=\"fas fa-user me-1\"></i>\r\n");
      out.write("                                        <span class=\"d-none d-md-inline\">Tài khoản</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-sign-in-alt me-2\"></i>Đăng nhập\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-user-plus me-2\"></i>Đăng ký\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cart-btn\">\r\n");
      out.write("                            <a href=\"cart.jsp\" class=\"btn btn-primary\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-cart me-1\"></i>\r\n");
      out.write("                                <span class=\"cart-count\">0</span>\r\n");
      out.write("                                <span class=\"d-none d-lg-inline ms-1\">Giỏ hàng</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Mobile Sidebar Navigation -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/mobile-sidebar.jsp", out, false);
      out.write("<!-- Hero Banner -->\r\n");
      out.write("    <section class=\"hero-banner py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-9\">\r\n");
      out.write("                    <div id=\"heroCarousel\" class=\"carousel slide hero-carousel\" data-bs-ride=\"carousel\">\r\n");
      out.write("                        <div class=\"carousel-indicators\">\r\n");
      out.write("                            <button type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide-to=\"0\" class=\"active\"></button>\r\n");
      out.write("                            <button type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide-to=\"1\"></button>\r\n");
      out.write("                            <button type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide-to=\"2\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-inner\">\r\n");
      out.write("                            <div class=\"carousel-item active\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/Banner2.jpg\" class=\"d-block w-100\" alt=\"Banner 1\" \r\n");
      out.write("                                     onerror=\"this.src='https://via.placeholder.com/800x400/ff6600/ffffff?text=GUNPLA+45th+Anniversary'\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("                                    <h3 class=\"banner-title\">GUNPLA 45th Anniversary</h3>\r\n");
      out.write("                                    <p class=\"banner-subtitle\">Perfect Grade Unleashed Nu Gundam</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/Banner1.jpg\" class=\"d-block w-100\" alt=\"Banner 2\"\r\n");
      out.write("                                     onerror=\"this.src='https://via.placeholder.com/800x400/0066cc/ffffff?text=Gundam+Base+Tour'\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("                                    <h3 class=\"banner-title\">The Gundam Base World Tour 2025</h3>\r\n");
      out.write("                                    <p class=\"banner-subtitle\">Khám phá bộ sưu tập mới nhất từ Bandai</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/sale.png\" class=\"d-block w-100\" alt=\"Banner 3\"\r\n");
      out.write("                                     onerror=\"this.src='https://via.placeholder.com/800x400/cc0066/ffffff?text=Special+Sale'\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("                                    <h3 class=\"banner-title\">Special Sale Event</h3>\r\n");
      out.write("                                    <p class=\"banner-subtitle\">Giảm giá lên đến 50% cho các sản phẩm chọn lọc</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("                            <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("                            <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <div class=\"side-banners\">\r\n");
      out.write("                        <div class=\"side-banner mb-3\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/sale.png\" class=\"img-fluid rounded\" alt=\"Sale Banner\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"side-banner\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/New.jpg\" class=\"img-fluid rounded\" alt=\"New Arrivals\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Main Content All Products -->\r\n");
      out.write("    <main class=\"container py-4\">\r\n");
      out.write("        <!-- Breadcrumb -->\r\n");
      out.write("        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("            <ol class=\"breadcrumb mb-3\">\r\n");
      out.write("                <li class=\"breadcrumb-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/\">Trang chủ</a></li>\r\n");
      out.write("                <li class=\"breadcrumb-item active\" aria-current=\"page\">Tất cả sản phẩm</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Sidebar bộ lọc -->\r\n");
      out.write("            <aside class=\"col-lg-3 mb-4\">\r\n");
      out.write("                <div class=\"card shadow-sm mb-3\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"filter-title\">Loại sản phẩm</div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"filterHG\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"filterHG\">High Grade (HG)</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"filterMG\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"filterMG\">Master Grade (MG)</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"filterRG\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"filterRG\">Real Grade (RG)</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"filterPG\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"filterPG\">Perfect Grade (PG)</label>\r\n");
      out.write("                        </div>                        <div class=\"filter-title\">Khoảng giá</div>\r\n");
      out.write("                        <input type=\"range\" class=\"form-range\" min=\"0\" max=\"5000000\" step=\"50000\" id=\"priceRange\" value=\"5000000\">\r\n");
      out.write("                        <div class=\"d-flex justify-content-between small\">\r\n");
      out.write("                            <span>0₫</span>\r\n");
      out.write("                            <span id=\"maxPriceDisplay\">5.000.000₫+</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"filter-title\">Thương hiệu</div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"filterBandai\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"filterBandai\">Bandai</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-check\">\r\n");
      out.write("                            <input class=\"form-check-input\" type=\"checkbox\" id=\"filterKhac\">\r\n");
      out.write("                            <label class=\"form-check-label\" for=\"filterKhac\">Khác</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("            <!-- Lưới sản phẩm -->\r\n");
      out.write("            <section class=\"col-lg-9\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("                    <h1 class=\"h4 fw-bold mb-0\">Tất cả sản phẩm</h1>                    <select class=\"form-select w-auto\" id=\"sortSelect\">\r\n");
      out.write("                        <option value=\"latest\">Sắp xếp: Mới nhất</option>\r\n");
      out.write("                        <option value=\"price_asc\">Giá tăng dần</option>\r\n");
      out.write("                        <option value=\"price_desc\">Giá giảm dần</option>\r\n");
      out.write("                        <option value=\"popular\">Bán chạy</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>                <div class=\"row g-3\" id=\"products-grid\">\r\n");
      out.write("                    <!-- Sản phẩm sẽ được load động từ database qua JavaScript -->\r\n");
      out.write("                    <!-- Loading placeholder -->\r\n");
      out.write("                    <div class=\"col-12 text-center\" id=\"products-loading\">\r\n");
      out.write("                        <div class=\"spinner-border text-primary\" role=\"status\">\r\n");
      out.write("                            <span class=\"visually-hidden\">Đang tải sản phẩm...</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"mt-2\">Đang tải sản phẩm từ database...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Fallback: Sản phẩm mẫu static (sẽ bị thay thế bởi dữ liệu động) -->\r\n");
      out.write("                    <div class=\"col-6 col-md-4 col-lg-3 fallback-product\">\r\n");
      out.write("                        <div class=\"card product-card h-100 border-0 shadow-sm\">\r\n");
      out.write("                            <img src=\"img/coll_1.jpg\" class=\"card-img-top product-img\" alt=\"Gundam 1\">\r\n");
      out.write("                            <div class=\"card-body p-2\">\r\n");
      out.write("                                <h6 class=\"card-title mb-1\">Gundam RX-78-2</h6>\r\n");
      out.write("                                <div class=\"mb-1\">\r\n");
      out.write("                                    <span class=\"price\">450.000₫</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"");
      out.print(request.getContextPath());
      out.write("/product-detail.jsp\" class=\"btn btn-sm btn-outline-primary w-100\">Xem chi tiết</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-6 col-md-4 col-lg-3 fallback-product\">\r\n");
      out.write("                        <div class=\"card product-card h-100 border-0 shadow-sm\">\r\n");
      out.write("                            <img src=\"img/coll_2.jpg\" class=\"card-img-top product-img\" alt=\"Gundam 2\">\r\n");
      out.write("                            <div class=\"card-body p-2\">\r\n");
      out.write("                                <h6 class=\"card-title mb-1\">Gundam Barbatos</h6>\r\n");
      out.write("                                <div class=\"mb-1\">\r\n");
      out.write("                                    <span class=\"price\">650.000₫</span>\r\n");
      out.write("                                    <span class=\"old-price ms-2\">800.000₫</span>\r\n");
      out.write("                                    <span class=\"discount-badge ms-2\">-19%</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"");
      out.print(request.getContextPath());
      out.write("/product-detail.jsp\" class=\"btn btn-sm btn-outline-primary w-100\">Xem chi tiết</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-6 col-md-4 col-lg-3 fallback-product\">\r\n");
      out.write("                        <div class=\"card product-card h-100 border-0 shadow-sm\">\r\n");
      out.write("                            <img src=\"img/coll_3.jpg\" class=\"card-img-top product-img\" alt=\"Gundam 3\">\r\n");
      out.write("                            <div class=\"card-body p-2\">\r\n");
      out.write("                                <h6 class=\"card-title mb-1\">Gundam Exia</h6>\r\n");
      out.write("                                <div class=\"mb-1\">\r\n");
      out.write("                                    <span class=\"price\">1.200.000₫</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"");
      out.print(request.getContextPath());
      out.write("/product-detail.jsp\" class=\"btn btn-sm btn-outline-primary w-100\">Xem chi tiết</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-6 col-md-4 col-lg-3 fallback-product\">\r\n");
      out.write("                        <div class=\"card product-card h-100 border-0 shadow-sm\">\r\n");
      out.write("                            <img src=\"img/coll_4.jpg\" class=\"card-img-top product-img\" alt=\"Gundam 4\">\r\n");
      out.write("                            <div class=\"card-body p-2\">\r\n");
      out.write("                                <h6 class=\"card-title mb-1\">Gundam Unicorn</h6>\r\n");
      out.write("                                <div class=\"mb-1\">\r\n");
      out.write("                                    <span class=\"price\">2.000.000₫</span>\r\n");
      out.write("                                    <span class=\"old-price ms-2\">2.500.000₫</span>\r\n");
      out.write("                                    <span class=\"discount-badge ms-2\">-20%</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"");
      out.print(request.getContextPath());
      out.write("/product-detail.jsp\" class=\"btn btn-sm btn-outline-primary w-100\">Xem chi tiết</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Phân trang -->\r\n");
      out.write("                <nav class=\"mt-4 d-flex justify-content-center\">\r\n");
      out.write("                    <ul class=\"pagination\">\r\n");
      out.write("                        <li class=\"page-item disabled\"><span class=\"page-link\">&laquo;</span></li>\r\n");
      out.write("                        <li class=\"page-item active\"><span class=\"page-link\">1</span></li>\r\n");
      out.write("                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                        <li class=\"page-item\"><a class=\"page-link\" href=\"#\">&raquo;</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer class=\"bg-dark text-white\">\r\n");
      out.write("        <div class=\"footer-top py-5\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h5 class=\"footer-title\">43 Gundam Hobby</h5>\r\n");
      out.write("                            <p class=\"footer-desc\">Chuyên cung cấp mô hình Gundam chính hãng với giá tốt nhất. Uy tín - Chất lượng - Dịch vụ tận tâm.</p>\r\n");
      out.write("                            <div class=\"store-info\">\r\n");
      out.write("                                <div class=\"info-item mb-2\">\r\n");
      out.write("                                    <i class=\"fas fa-map-marker-alt me-2\"></i>\r\n");
      out.write("                                    <span>59 Lê Đình Diên, Cẩm Lệ, Đà Nẵng</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info-item mb-2\">\r\n");
      out.write("                                    <i class=\"fas fa-phone me-2\"></i>\r\n");
      out.write("                                    <a href=\"tel:0385546145\" class=\"text-white\">0385546145 (8h-20h)</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info-item\">\r\n");
      out.write("                                    <i class=\"fas fa-envelope me-2\"></i>\r\n");
      out.write("                                    <a href=\"mailto:43gundamhobby@gmail.com\" class=\"text-white\">43gundamhobby@gmail.com</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Sản phẩm</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Gundam Bandai</a></li>\r\n");
      out.write("                                <li><a href=\"#\">High Grade (HG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Master Grade (MG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Real Grade (RG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Perfect Grade (PG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Metal Build</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Dịch vụ</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Hàng Pre-Order</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Dụng cụ & Phụ kiện</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Hướng dẫn lắp ráp</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Sơn & Trang trí</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Bảo hành sản phẩm</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Chính sách</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Chính sách bảo mật</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Chính sách thanh toán</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Chính sách vận chuyển</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Chính sách đổi trả</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Quy định sử dụng</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Hỗ trợ</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Liên hệ</a></li>\r\n");
      out.write("                                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Hướng dẫn đặt hàng</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Tra cứu đơn hàng</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Hỗ trợ kỹ thuật</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-social py-4 bg-darker\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <h6 class=\"social-title mb-3\">Theo dõi chúng tôi</h6>\r\n");
      out.write("                        <div class=\"social-links\">\r\n");
      out.write("                            <a href=\"https://www.facebook.com/BANDAIHobbysite.EN\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link facebook\">\r\n");
      out.write("                                <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                                <span>Facebook</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"https://www.youtube.com/@GundamInfo\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link youtube\">\r\n");
      out.write("                                <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("                                <span>Youtube</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"https://www.tiktok.com/@bandainamcoasiahobby_?is_from_webapp=1&sender_device=pc\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link tiktok\">\r\n");
      out.write("                                <i class=\"fab fa-tiktok\"></i>\r\n");
      out.write("                                <span>TikTok</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"https://www.instagram.com/bandaihobbyhk/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link instagram\">\r\n");
      out.write("                                <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                                <span>Instagram</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"newsletter\">\r\n");
      out.write("                            <h6 class=\"newsletter-title mb-3\">Đăng ký nhận tin</h6>\r\n");
      out.write("                            <form class=\"newsletter-form\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"email\" class=\"form-control\" placeholder=\"Nhập email của bạn...\">\r\n");
      out.write("                                    <button class=\"btn btn-primary\" type=\"submit\">\r\n");
      out.write("                                        <i class=\"fas fa-paper-plane\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-bottom py-3 bg-darker border-top border-secondary\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <p class=\"copyright mb-0\">&copy; 2025 43 Gundam Hobby. All rights reserved.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                        <div class=\"payment-methods\">\r\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=VISA\" alt=\"Visa\" class=\"payment-icon\">\r\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=MC\" alt=\"Mastercard\" class=\"payment-icon\">\r\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=COD\" alt=\"COD\" class=\"payment-icon\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Back to Top Button -->\r\n");
      out.write("    <button class=\"back-to-top\" id=\"backToTop\">\r\n");
      out.write("        <i class=\"fas fa-chevron-up\"></i>\r\n");
      out.write("    </button>    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- All Products Dynamic Manager -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/all-products-manager.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    // Function đăng xuất cho OAuth2\r\n");
      out.write("    function logoutUser() {\r\n");
      out.write("        if (confirm('Bạn có chắc chắn muốn đăng xuất?')) {\r\n");
      out.write("            // Gọi API logout của Spring Security OAuth2\r\n");
      out.write("            fetch('/logout', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: {\r\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("                }\r\n");
      out.write("            }).then(() => {\r\n");
      out.write("                // Clear session storage\r\n");
      out.write("                sessionStorage.clear();\r\n");
      out.write("                localStorage.clear();\r\n");
      out.write("                \r\n");
      out.write("                // Redirect về trang chủ\r\n");
      out.write("                window.location.href = '/';\r\n");
      out.write("            }).catch(error => {\r\n");
      out.write("                console.error('Logout error:', error);\r\n");
      out.write("                // Fallback: redirect về trang chủ dù có lỗi\r\n");
      out.write("                window.location.href = '/';\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Hiện/ẩn popup danh mục sản phẩm\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        var btn = document.getElementById('categoryBtn');\r\n");
      out.write("        var popup = document.getElementById('categoryPopup');\r\n");
      out.write("        if (btn && popup) {\r\n");
      out.write("            btn.addEventListener('mouseenter', function() {\r\n");
      out.write("                popup.classList.add('show');\r\n");
      out.write("            });\r\n");
      out.write("            btn.addEventListener('mouseleave', function() {\r\n");
      out.write("                setTimeout(function(){\r\n");
      out.write("                    if (!popup.matches(':hover')) popup.classList.remove('show');\r\n");
      out.write("                }, 100);\r\n");
      out.write("            });\r\n");
      out.write("            popup.addEventListener('mouseenter', function() {\r\n");
      out.write("                popup.classList.add('show');\r\n");
      out.write("            });\r\n");
      out.write("            popup.addEventListener('mouseleave', function() {\r\n");
      out.write("                popup.classList.remove('show');\r\n");
      out.write("            });\r\n");
      out.write("            // Mobile: click để toggle\r\n");
      out.write("            btn.addEventListener('click', function(e) {\r\n");
      out.write("                if (window.innerWidth < 992) {\r\n");
      out.write("                    popup.classList.toggle('show');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            // Click ngoài để ẩn\r\n");
      out.write("            document.addEventListener('click', function(e) {\r\n");
      out.write("                if (!btn.contains(e.target) && !popup.contains(e.target)) {\r\n");
      out.write("                    popup.classList.remove('show');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Real-time price range display update\r\n");
      out.write("        const priceRange = document.getElementById('priceRange');\r\n");
      out.write("        const maxPriceDisplay = document.getElementById('maxPriceDisplay');\r\n");
      out.write("        if (priceRange && maxPriceDisplay) {\r\n");
      out.write("            priceRange.addEventListener('input', function(e) {\r\n");
      out.write("                const value = parseInt(e.target.value);\r\n");
      out.write("                if (value >= 5000000) {\r\n");
      out.write("                    maxPriceDisplay.textContent = '5.000.000₫+';\r\n");
      out.write("                } else {\r\n");
      out.write("                    maxPriceDisplay.textContent = new Intl.NumberFormat('vi-VN', {\r\n");
      out.write("                        style: 'currency',\r\n");
      out.write("                        currency: 'VND'\r\n");
      out.write("                    }).format(value);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Hide loading placeholder when products are loaded\r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("            const loadingElement = document.getElementById('products-loading');\r\n");
      out.write("            const fallbackProducts = document.querySelectorAll('.fallback-product');\r\n");
      out.write("            \r\n");
      out.write("            if (loadingElement) {\r\n");
      out.write("                loadingElement.style.display = 'none';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Hide fallback products after dynamic loading\r\n");
      out.write("            if (window.allProductsManager && window.allProductsManager.allProducts.length > 0) {\r\n");
      out.write("                fallbackProducts.forEach(product => {\r\n");
      out.write("                    product.style.display = 'none';\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }, 2000);\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Hamburger Menu Script -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/hamburger-menu.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Search Autocomplete Script -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/search-autocomplete.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Avatar Utils -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/avatar-utils.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Authentication and Navbar Scripts -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/auth-sync.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/navbar-manager.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/google-oauth-clean.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/navbar-fix.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Force check auth state after page load -->\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // Force check auth state multiple times to ensure sync\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                if (window.authSyncManager) {\r\n");
      out.write("                    window.authSyncManager.forceRefresh();\r\n");
      out.write("                }\r\n");
      out.write("            }, 100);\r\n");
      out.write("            \r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                if (window.authSyncManager) {\r\n");
      out.write("                    window.authSyncManager.forceRefresh();\r\n");
      out.write("                }\r\n");
      out.write("            }, 500);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
