/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-07-11 11:26:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class favorites_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/mobile-sidebar.jsp", Long.valueOf(1752230795387L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sản phẩm yêu thích - 43 Gundam Hobby</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/category-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-darkmode.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-bg-orange.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-menu-white.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/hamburger-menu.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"bg-white shadow-sm sticky-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center py-3\">\r\n");
      out.write("                <!-- Logo Section with Hamburger Menu -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6\">\r\n");
      out.write("                    <div class=\"header-logo-section\">\r\n");
      out.write("                        <!-- Hamburger Menu (Mobile) -->\r\n");
      out.write("                        <button class=\"hamburger-menu\" id=\"hamburgerBtn\" aria-label=\"Menu\">\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"logo\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" alt=\"43 Gundam Logo\" class=\"logo-img\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Search Section -->\r\n");
      out.write("                <div class=\"col-lg-6 col-md-4 col-12 order-lg-2 order-md-2 order-3\">\r\n");
      out.write("                    <div class=\"header-center-section\">\r\n");
      out.write("                        <div class=\"search-container w-100\">\r\n");
      out.write("                            <form class=\"search-form\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control search-input\" placeholder=\"Tìm kiếm sản phẩm...\">\r\n");
      out.write("                                    <button class=\"btn btn-search\" type=\"submit\">\r\n");
      out.write("                                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Actions Section -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 order-lg-3 order-md-3 order-2\">\r\n");
      out.write("                    <div class=\"header-actions-section\">\r\n");
      out.write("                        <div class=\"account-menu me-3\">\r\n");
      out.write("                            ");

                                Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
                                String userName = (String) session.getAttribute("userName");
                                String userPicture = (String) session.getAttribute("userPicture");
                                
                                if (isLoggedIn != null && isLoggedIn) {
                            
      out.write("<!-- User logged in -->\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-toggle text-decoration-none d-flex align-items-center\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                        ");
 if (userPicture != null && !userPicture.isEmpty()) { 
      out.write("<img src=\"");
      out.print( userPicture );
      out.write("\" alt=\"Avatar\" class=\"rounded-circle me-2 avatar-32\">\r\n");
      out.write("                                        ");
 } else { 
      out.write("<i class=\"fas fa-user-circle me-2 user-icon-32\"></i>\r\n");
      out.write("                                        ");
 } 
      out.write("<span class=\"text-dark d-none d-md-inline\">Xin chào, ");
      out.print( userName != null ? userName : "User" );
      out.write("</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end z-index-1050\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/profile.jsp\"><i class=\"fas fa-user me-2\"></i>Hồ sơ khách hàng</a></li>\r\n");
      out.write("                                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item text-danger\" href=\"#\" onclick=\"logoutUser()\"><i class=\"fas fa-sign-out-alt me-2\"></i>Đăng xuất</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");

                                } else {
                            
      out.write("<!-- User not logged in -->\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-outline-primary dropdown-toggle\" \r\n");
      out.write("                                       id=\"accountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                        <i class=\"fas fa-user me-1\"></i>\r\n");
      out.write("                                        <span class=\"d-none d-md-inline\">Tài khoản</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-sign-in-alt me-2\"></i>Đăng nhập\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-user-plus me-2\"></i>Đăng ký\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");

                                }
                            
      out.write("</div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"cart-section\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/cart.jsp\" class=\"btn btn-outline-primary position-relative\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                                <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger\">\r\n");
      out.write("                                    0\r\n");
      out.write("                                    <span class=\"visually-hidden\">items in cart</span>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Include Mobile Sidebar -->\r\n");
      out.write("    ");
      out.write("<!-- Universal Sidebar Navigation (works on all screen sizes) -->\r\n");
      out.write("<div class=\"mobile-sidebar\" id=\"mobileSidebar\">\r\n");
      out.write("    <button class=\"sidebar-close\" id=\"sidebarClose\" aria-label=\"Đóng menu\">&times;</button>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar-header\">\r\n");
      out.write("        <h4><i class=\"fas fa-rocket me-2\"></i>GundamHobby Menu</h4>\r\n");
      out.write("        <p class=\"mb-0 text-muted small\">✨ Khám phá thế giới mô hình tuyệt vời</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Category Section in Sidebar -->\r\n");
      out.write("    <div class=\"category-section\">\r\n");
      out.write("        <h5><i class=\"fas fa-layer-group me-2\"></i>Danh Mục Sản Phẩm</h5>\r\n");
      out.write("        <ul class=\"category-list\">\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-robot me-2\"></i>Gundam Bandai</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-industry me-2\"></i>Mô hình Trung</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-gem me-2\"></i>Metal Build - Diecast</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-tools me-2\"></i>Dụng cụ - Tool</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-puzzle-piece me-2\"></i>Phụ kiện - Base</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-dragon me-2\"></i>Mô hình Dragon Ball</a></li>\r\n");
      out.write("            <li><a href=\"#\"><i class=\"fas fa-palette me-2\"></i>Sơn - Decal</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"sidebar-menu\">\r\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/\"><i class=\"fas fa-home me-2\"></i>Trang chủ</a></li>\r\n");
      out.write("        <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/all-products.jsp\"><i class=\"fas fa-th-large me-2\"></i>Tất cả sản phẩm</a></li>\r\n");
      out.write("        <li><a href=\"#\"><i class=\"fas fa-star me-2\"></i>Hàng mới về</a></li>\r\n");
      out.write("        <li><a href=\"#\"><i class=\"fas fa-clock me-2\"></i>Hàng Pre-order</a></li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#phukienSubmenu\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"fas fa-cubes me-2\"></i>Phụ kiện & Mô hình <i class=\"fas fa-chevron-down float-end\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"collapse submenu\" id=\"phukienSubmenu\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-tools me-2\"></i>Dụng cụ - Tool</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-puzzle-piece me-2\"></i>Phụ kiện - Base</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-dragon me-2\"></i>Mô hình Dragon Ball</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#\" data-bs-toggle=\"collapse\" data-bs-target=\"#bandaiSubmenu\" aria-expanded=\"false\">\r\n");
      out.write("                <i class=\"fas fa-robot me-2\"></i>Bandai Collection <i class=\"fas fa-chevron-down float-end\"></i>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"collapse submenu\" id=\"bandaiSubmenu\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-award me-2\"></i>High Grade (HG)</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-trophy me-2\"></i>Master Grade (MG)</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-medal me-2\"></i>Real Grade (RG)</a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fas fa-crown me-2\"></i>Perfect Grade (PG)</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li><a href=\"favorites.jsp\"><i class=\"fas fa-heart me-2\"></i>Yêu thích</a></li>\r\n");
      out.write("        <li><a href=\"#\"><i class=\"fas fa-user me-2\"></i>Tài khoản</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Additional Info Section for Desktop -->\r\n");
      out.write("    <div class=\"sidebar-footer d-none d-lg-block\">\r\n");
      out.write("        <div class=\"contact-info mt-4 p-3 rounded\">\r\n");
      out.write("            <h6 class=\"mb-3\"><i class=\"fas fa-headset me-2\"></i>Liên hệ hỗ trợ</h6>\r\n");
      out.write("            <p class=\"mb-2 small\"><i class=\"fas fa-map-marker-alt me-2\"></i>59 Lê Đình Diên, Cẩm Lệ, Đà Nẵng</p>\r\n");
      out.write("            <p class=\"mb-2 small\"><i class=\"fas fa-phone-alt me-2\"></i>0385 546 145</p>\r\n");
      out.write("            <p class=\"mb-2 small\"><i class=\"fas fa-envelope me-2\"></i>43gundamhobby@gmail.com</p>\r\n");
      out.write("            <p class=\"mb-0 small\"><i class=\"fas fa-clock me-2\"></i>8:00 - 22:00 hàng ngày</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Sidebar Overlay -->\r\n");
      out.write("<div class=\"mobile-overlay\" id=\"mobileOverlay\"></div>\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("    <main class=\"container py-4\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Breadcrumb -->\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                    <ol class=\"breadcrumb\">\r\n");
      out.write("                        <li class=\"breadcrumb-item\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/\">Trang chủ</a></li>\r\n");
      out.write("                        <li class=\"breadcrumb-item active\" aria-current=\"page\">Sản phẩm yêu thích</li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Main Content Area -->\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("                    <h1 class=\"h3 fw-bold mb-0\">\r\n");
      out.write("                        <i class=\"fas fa-heart text-danger me-2\"></i>\r\n");
      out.write("                        Sản phẩm yêu thích\r\n");
      out.write("                    </h1>\r\n");
      out.write("                    <span class=\"badge bg-primary\" id=\"favoritesCount\">0 sản phẩm</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Login Required Message -->\r\n");
      out.write("                <div class=\"alert alert-info\" id=\"loginRequiredMessage\" style=\"display: none;\">\r\n");
      out.write("                    <i class=\"fas fa-info-circle me-2\"></i>\r\n");
      out.write("                    Vui lòng <a href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\" class=\"alert-link\">đăng nhập</a> để xem danh sách sản phẩm yêu thích của bạn.\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Empty Favorites Message -->\r\n");
      out.write("                <div class=\"text-center py-5\" id=\"emptyFavoritesMessage\" style=\"display: none;\">\r\n");
      out.write("                    <i class=\"fas fa-heart-broken text-muted\" style=\"font-size: 4rem;\"></i>\r\n");
      out.write("                    <h4 class=\"mt-3 text-muted\">Chưa có sản phẩm yêu thích</h4>\r\n");
      out.write("                    <p class=\"text-muted\">Hãy thêm những sản phẩm mà bạn yêu thích vào danh sách này!</p>\r\n");
      out.write("                    <a href=\"");
      out.print(request.getContextPath());
      out.write("/all-products.jsp\" class=\"btn btn-primary\">\r\n");
      out.write("                        <i class=\"fas fa-shopping-bag me-2\"></i>Khám phá sản phẩm\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Products Grid -->\r\n");
      out.write("                <div class=\"row g-3\" id=\"favoritesGrid\">\r\n");
      out.write("                    <!-- Loading spinner -->\r\n");
      out.write("                    <div class=\"col-12 text-center\" id=\"loadingSpinner\">\r\n");
      out.write("                        <div class=\"spinner-border text-primary\" role=\"status\">\r\n");
      out.write("                            <span class=\"visually-hidden\">Đang tải...</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"mt-2\">Đang tải sản phẩm yêu thích...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"bg-dark text-white py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <h5>43 Gundam Hobby</h5>\r\n");
      out.write("                    <p class=\"mb-0\">Chuyên cung cấp mô hình Gundam chính hãng</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <h5>Liên hệ</h5>\r\n");
      out.write("                    <p class=\"mb-1\"><i class=\"fas fa-map-marker-alt me-2\"></i>59 Lê Đình Diên, Cẩm Lệ, Đà Nẵng</p>\r\n");
      out.write("                    <p class=\"mb-1\"><i class=\"fas fa-phone me-2\"></i>0385 546 145</p>\r\n");
      out.write("                    <p class=\"mb-0\"><i class=\"fas fa-envelope me-2\"></i>43gundamhobby@gmail.com</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4\">\r\n");
      out.write("                    <h5>Giờ mở cửa</h5>\r\n");
      out.write("                    <p class=\"mb-0\">8:00 - 22:00 hàng ngày</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Custom JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/hamburger-menu.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/auth.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/favorites-manager.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
