/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-07-14 17:27:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>43 Gundam Hobby - Mô hình Gundam chính hãng</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/layout-sizing.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/category-popup.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-darkmode.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-bg-orange.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-menu-white.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/hamburger-menu.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-fix.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/user-avatar.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/login-anhobby.css\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Header -->\n");
      out.write("    <header class=\"bg-white shadow-sm sticky-top\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row align-items-center py-3\">\n");
      out.write("                <!-- Logo Section with Hamburger Menu -->\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6\">\n");
      out.write("                    <div class=\"header-logo-section\">\n");
      out.write("                        <!-- Hamburger Menu (Mobile) -->\n");
      out.write("                        <button class=\"hamburger-menu\" id=\"hamburgerBtn\" aria-label=\"Menu\">\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                            <span class=\"line\"></span>\n");
      out.write("                        </button>\n");
      out.write("                        \n");
      out.write("                        <div class=\"logo\">\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" alt=\"43 Gundam Logo\" class=\"logo-img\">\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Search Section -->\n");
      out.write("                <div class=\"col-lg-6 col-md-4 col-12 order-lg-2 order-md-2 order-3\">\n");
      out.write("                    <div class=\"header-center-section\">\n");
      out.write("                        <div class=\"search-container w-100\">\n");
      out.write("                            <form class=\"search-form\" action=\"");
      out.print(request.getContextPath());
      out.write("/search.jsp\" method=\"get\">\n");
      out.write("                                <div class=\"input-group\">\n");
      out.write("                                    <input type=\"text\" name=\"q\" class=\"form-control search-input\" \n");
      out.write("                                           placeholder=\"Tìm kiếm sản phẩm...\" autocomplete=\"off\">\n");
      out.write("                                    <button class=\"btn btn-search\" type=\"submit\">\n");
      out.write("                                        <i class=\"fas fa-search\"></i>\n");
      out.write("                                    </button>\n");
      out.write("                                </div>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <!-- Actions Section -->\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 order-lg-3 order-md-3 order-2\">\n");
      out.write("                    <div class=\"header-actions-section\">\n");
      out.write("                        <div class=\"account-menu me-3\">\n");
      out.write("                            <!-- User Info (visible when logged in) -->\n");
      out.write("                            <div id=\"nav-user-info\" class=\"d-none\">\n");
      out.write("                                <div class=\"dropdown\">\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-outline-success dropdown-toggle d-flex align-items-center\" \n");
      out.write("                                       id=\"userAccountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\n");
      out.write("                                        <div class=\"user-avatar-container me-2\">\n");
      out.write("                                            <img id=\"userAvatarImage\" \n");
      out.write("                                                 src=\"");
      out.print(request.getContextPath());
      out.write("/img/placeholder.jpg\" \n");
      out.write("                                                 alt=\"User Avatar\" \n");
      out.write("                                                 class=\"user-avatar rounded-circle\"\n");
      out.write("                                                 style=\"width: 32px; height: 32px; object-fit: cover;\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <span class=\"d-none d-md-inline\">\n");
      out.write("                                            <span class=\"greeting-text\">Xin chào</span>\n");
      out.write("                                            <span id=\"userDisplayName\" class=\"fw-bold\">User</span>\n");
      out.write("                                        </span>\n");
      out.write("                                        <span class=\"d-md-none\">\n");
      out.write("                                            <span id=\"userDisplayNameMobile\" class=\"fw-bold\">User</span>\n");
      out.write("                                        </span>\n");
      out.write("                                    </a>\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end\">\n");
      out.write("                                        <li><h6 class=\"dropdown-header d-flex align-items-center\">\n");
      out.write("                                            <img id=\"userAvatarDropdown\" \n");
      out.write("                                                 src=\"");
      out.print(request.getContextPath());
      out.write("/img/placeholder.jpg\" \n");
      out.write("                                                 alt=\"User Avatar\" \n");
      out.write("                                                 class=\"user-avatar-small rounded-circle me-2\"\n");
      out.write("                                                 style=\"width: 24px; height: 24px; object-fit: cover;\">\n");
      out.write("                                            <span id=\"userFullName\">User Name</span>\n");
      out.write("                                        </h6></li>\n");
      out.write("                                        <li><hr class=\"dropdown-divider\"></li>\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/profile.jsp\">\n");
      out.write("                                            <i class=\"fas fa-user-edit me-2\"></i>Thông tin tài khoản\n");
      out.write("                                        </a></li>\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                                            <i class=\"fas fa-shopping-bag me-2\"></i>Đơn hàng của tôi\n");
      out.write("                                        </a></li>\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                                            <i class=\"fas fa-heart me-2\"></i>Sản phẩm yêu thích\n");
      out.write("                                        </a></li>\n");
      out.write("                                        <li><hr class=\"dropdown-divider\"></li>\n");
      out.write("                                        <li><a class=\"dropdown-item text-danger\" href=\"#\" onclick=\"userLogout()\">\n");
      out.write("                                            <i class=\"fas fa-sign-out-alt me-2\"></i>Đăng xuất\n");
      out.write("                                        </a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            \n");
      out.write("                            <!-- Login Button (visible when not logged in) -->\n");
      out.write("                            <div id=\"nav-login-btn\">\n");
      out.write("                                <div class=\"dropdown\">\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-outline-primary dropdown-toggle\" \n");
      out.write("                                       id=\"accountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\n");
      out.write("                                        <i class=\"fas fa-user me-1\"></i>\n");
      out.write("                                        <span class=\"d-none d-md-inline\">Tài khoản</span>\n");
      out.write("                                    </a>\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end\">\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\">\n");
      out.write("                                            <i class=\"fas fa-sign-in-alt me-2\"></i>Đăng nhập\n");
      out.write("                                        </a></li>\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">\n");
      out.write("                                            <i class=\"fas fa-user-plus me-2\"></i>Đăng ký\n");
      out.write("                                        </a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"cart-btn\">\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">\n");
      out.write("                                <i class=\"fas fa-shopping-cart me-1\"></i>\n");
      out.write("                                <span class=\"cart-count\">0</span>\n");
      out.write("                                <span class=\"d-none d-lg-inline ms-1\">Giỏ hàng</span>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>    <!-- Mobile Sidebar Navigation -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/mobile-sidebar.jsp", out, false);
      out.write("<!-- Login Form -->\n");
      out.write("    <div class=\"container d-flex flex-column align-items-center justify-content-center min-height-70vh\">\n");
      out.write("        <div class=\"login-title mt-4\">Đăng nhập tài khoản</div>\n");
      out.write("        \n");
      out.write("        <div class=\"login-form-box mx-auto\" id=\"login-form\">\n");
      out.write("            <form id=\"loginForm\" action=\"");
      out.print(request.getContextPath());
      out.write("/api/login\" method=\"post\" autocomplete=\"off\">\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"email\" class=\"form-label\">Email *</label>\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required autocomplete=\"off\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"mb-3\">\n");
      out.write("                    <label for=\"password\" class=\"form-label\">Mật khẩu *</label>\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required autocomplete=\"off\">\n");
      out.write("                </div>\n");
      out.write("                <button type=\"submit\" class=\"btn btn-login w-100\">Đăng nhập</button>\n");
      out.write("            </form>\n");
      out.write("            <div class=\"text-center mb-3\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-link p-0 text-decoration-none forgot-password-link\" onclick=\"window.location.href='");
      out.print(request.getContextPath());
      out.write("/forgot-password.jsp'\">\n");
      out.write("                    Quên mật khẩu?\n");
      out.write("                </button>\n");
      out.write("                <br>\n");
      out.write("                <small class=\"text-muted\">hoặc</small>\n");
      out.write("                <br>\n");
      out.write("                <a href=\"");
      out.print(request.getContextPath());
      out.write("/forgot-password.jsp\" class=\"text-primary\">Khôi phục mật khẩu</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"login-divider\">Hoặc đăng nhập bằng</div>\n");
      out.write("            <button type=\"button\" class=\"btn btn-outline-danger social-login-btn\" id=\"google-sign-in-btn\">\n");
      out.write("                <i class=\"fab fa-google me-2\"></i>Google\n");
      out.write("            </button>\n");
      out.write("            <div class=\"register-link\">\n");
      out.write("                Bạn chưa có tài khoản? <a href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">Đăng ký tại đây</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- User Info Display (hidden by default) -->\n");
      out.write("        <div id=\"user-info\" class=\"login-form-box mx-auto d-none\">\n");
      out.write("            <!-- Content will be populated by JavaScript -->\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer class=\"bg-dark text-white\">\n");
      out.write("        <div class=\"footer-top py-5\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("                        <div class=\"footer-section\">\n");
      out.write("                            <h5 class=\"footer-title\">43 Gundam Hobby</h5>\n");
      out.write("                            <p class=\"footer-desc\">Chuyên cung cấp mô hình Gundam chính hãng với giá tốt nhất. Uy tín - Chất lượng - Dịch vụ tận tâm.</p>\n");
      out.write("                            <div class=\"store-info\">\n");
      out.write("                                <div class=\"info-item mb-2\">\n");
      out.write("                                    <i class=\"fas fa-map-marker-alt me-2\"></i>\n");
      out.write("                                    <span>59 Lê Đình Diên, Cẩm Lệ, Đà Nẵng</span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"info-item mb-2\">\n");
      out.write("                                    <i class=\"fas fa-phone me-2\"></i>\n");
      out.write("                                    <a href=\"tel:0385546145\" class=\"text-white\">0385546145 (8h-20h)</a>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"info-item\">\n");
      out.write("                                    <i class=\"fas fa-envelope me-2\"></i>\n");
      out.write("                                    <a href=\"mailto:43gundamhobby@gmail.com\" class=\"text-white\">43gundamhobby@gmail.com</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\n");
      out.write("                        <div class=\"footer-section\">\n");
      out.write("                            <h6 class=\"footer-title\">Sản phẩm</h6>\n");
      out.write("                            <ul class=\"footer-links\">\n");
      out.write("                                <li><a href=\"#\">Gundam Bandai</a></li>\n");
      out.write("                                <li><a href=\"#\">High Grade (HG)</a></li>\n");
      out.write("                                <li><a href=\"#\">Master Grade (MG)</a></li>\n");
      out.write("                                <li><a href=\"#\">Real Grade (RG)</a></li>\n");
      out.write("                                <li><a href=\"#\">Perfect Grade (PG)</a></li>\n");
      out.write("                                <li><a href=\"#\">Metal Build</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\n");
      out.write("                        <div class=\"footer-section\">\n");
      out.write("                            <h6 class=\"footer-title\">Dịch vụ</h6>\n");
      out.write("                            <ul class=\"footer-links\">\n");
      out.write("                                <li><a href=\"#\">Hàng Pre-Order</a></li>\n");
      out.write("                                <li><a href=\"#\">Dụng cụ & Phụ kiện</a></li>\n");
      out.write("                                <li><a href=\"#\">Hướng dẫn lắp ráp</a></li>\n");
      out.write("                                <li><a href=\"#\">Sơn & Trang trí</a></li>\n");
      out.write("                                <li><a href=\"#\">Bảo hành sản phẩm</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\n");
      out.write("                        <div class=\"footer-section\">\n");
      out.write("                            <h6 class=\"footer-title\">Chính sách</h6>\n");
      out.write("                            <ul class=\"footer-links\">\n");
      out.write("                                <li><a href=\"#\">Chính sách bảo mật</a></li>\n");
      out.write("                                <li><a href=\"#\">Chính sách thanh toán</a></li>\n");
      out.write("                                <li><a href=\"#\">Chính sách vận chuyển</a></li>\n");
      out.write("                                <li><a href=\"#\">Chính sách đổi trả</a></li>\n");
      out.write("                                <li><a href=\"#\">Quy định sử dụng</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\n");
      out.write("                        <div class=\"footer-section\">\n");
      out.write("                            <h6 class=\"footer-title\">Hỗ trợ</h6>\n");
      out.write("                            <ul class=\"footer-links\">\n");
      out.write("                                <li><a href=\"#\">Liên hệ</a></li>\n");
      out.write("                                <li><a href=\"#\">FAQ</a></li>\n");
      out.write("                                <li><a href=\"#\">Hướng dẫn đặt hàng</a></li>\n");
      out.write("                                <li><a href=\"#\">Tra cứu đơn hàng</a></li>\n");
      out.write("                                <li><a href=\"#\">Hỗ trợ kỹ thuật</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-social py-4 bg-darker\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row align-items-center\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <h6 class=\"social-title mb-3\">Theo dõi chúng tôi</h6>\n");
      out.write("                        <div class=\"social-links\">\n");
      out.write("                            <a href=\"https://www.facebook.com/BANDAIHobbysite.EN\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link facebook\">\n");
      out.write("                                <i class=\"fab fa-facebook-f\"></i>\n");
      out.write("                                <span>Facebook</span>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"https://www.youtube.com/@GundamInfo\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link youtube\">\n");
      out.write("                                <i class=\"fab fa-youtube\"></i>\n");
      out.write("                                <span>Youtube</span>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"https://www.tiktok.com/@bandainamcoasiahobby_?is_from_webapp=1&sender_device=pc\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link tiktok\">\n");
      out.write("                                <i class=\"fab fa-tiktok\"></i>\n");
      out.write("                                <span>TikTok</span>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"https://www.instagram.com/bandaihobbyhk/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"social-link instagram\">\n");
      out.write("                                <i class=\"fab fa-instagram\"></i>\n");
      out.write("                                <span>Instagram</span>\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <div class=\"newsletter\">\n");
      out.write("                            <h6 class=\"newsletter-title mb-3\">Đăng ký nhận tin</h6>\n");
      out.write("                            <form class=\"newsletter-form\">\n");
      out.write("                                <div class=\"input-group\">\n");
      out.write("                                    <input type=\"email\" class=\"form-control\" placeholder=\"Nhập email của bạn...\">\n");
      out.write("                                    <button class=\"btn btn-primary\" type=\"submit\">\n");
      out.write("                                        <i class=\"fas fa-paper-plane\"></i>\n");
      out.write("                                    </button>\n");
      out.write("                                </div>\n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-bottom py-3 bg-darker border-top border-secondary\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row align-items-center\">\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <p class=\"copyright mb-0\">&copy; 2025 43 Gundam Hobby. All rights reserved.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6 text-md-end\">\n");
      out.write("                        <div class=\"payment-methods\">\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=VISA\" alt=\"Visa\" class=\"payment-icon\">\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=MC\" alt=\"Mastercard\" class=\"payment-icon\">\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=COD\" alt=\"COD\" class=\"payment-icon\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Menu -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"mainNavbar\">\n");
      out.write("                <ul class=\"navbar-nav mx-auto mb-2 mb-lg-0\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link fw-bold\" href=\"");
      out.print(request.getContextPath());
      out.write("/all-products.jsp\">Tất cả sản phẩm</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link fw-bold\" href=\"#\">HÀNG MỚI VỀ</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                        <a class=\"nav-link fw-bold\" href=\"#\">HÀNG PRE-ORDER</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item dropdown\">\n");
      out.write("                        <a class=\"nav-link dropdown-toggle fw-bold\" href=\"#\" id=\"phukienDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("                            PHỤ KIỆN & MÔ HÌNH\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"phukienDropdown\">\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Dụng cụ - Tool</a></li>\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Phụ kiện - Base</a></li>\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Mô hình Dragon Ball</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item dropdown\">\n");
      out.write("                        <a class=\"nav-link dropdown-toggle fw-bold\" href=\"#\" id=\"bandaiDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("                            BANDAI\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"bandaiDropdown\">\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">High Grade (HG)</a></li>\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Master Grade (MG)</a></li>\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Real Grade (RG)</a></li>\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Perfect Grade (PG)</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- Back to Top Button -->\n");
      out.write("    <button class=\"back-to-top\" id=\"backToTop\">\n");
      out.write("        <i class=\"fas fa-chevron-up\"></i>\n");
      out.write("    </button>\n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- MD5 Library for Gravatar -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/md5.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Email to Google Converter -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/email-to-google-converter.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Unified Navbar Manager -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/unified-navbar-manager.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Google OAuth Handler -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/google-oauth-handler.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Login Script -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/login-clean.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Hamburger Menu -->\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/hamburger-menu.js\"></script>\n");
      out.write("    \n");
      out.write("    <!-- Login Fallback Handler (if API is not available) -->\n");
      out.write("    <!-- <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/login-fallback.js\"></script> -->\n");
      out.write("    \n");
      out.write("    <!-- Hamburger Menu Script -->\n");
      out.write("    <!-- <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/hamburger-menu.js\"></script> -->\n");
      out.write("    \n");
      out.write("    <!-- Login Debug Helper (Development Only) -->\n");
      out.write("    <!-- <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/login-debug-helper.js\"></script> -->\n");
      out.write("    \n");
      out.write("    <!-- Login Debug Fix - Sửa lỗi navbar sau login -->\n");
      out.write("    <!-- <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/login-debug-fix.js\"></script> -->\n");
      out.write("    \n");
      out.write("    <!-- Comprehensive Auth Manager - Đảm bảo auth state luôn đúng -->\n");
      out.write("    <!-- <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/comprehensive-auth-manager.js\"></script> -->\n");
      out.write("    \n");
      out.write("    <!-- Context Path Test Script (Development Only) -->\n");
      out.write("    <!-- <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/context-path-test.js\"></script> -->\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        // Back to top functionality\n");
      out.write("        const backToTopBtn = document.getElementById('backToTop');\n");
      out.write("        \n");
      out.write("        window.addEventListener('scroll', () => {\n");
      out.write("            if (window.pageYOffset > 300) {\n");
      out.write("                backToTopBtn.classList.add('show');\n");
      out.write("            } else {\n");
      out.write("                backToTopBtn.classList.remove('show');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        backToTopBtn.addEventListener('click', () => {\n");
      out.write("            window.scrollTo({\n");
      out.write("                top: 0,\n");
      out.write("                behavior: 'smooth'\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        // Set context path globally for JavaScript access\n");
      out.write("        window.APP_CONTEXT_PATH = '");
      out.print(request.getContextPath());
      out.write("';\n");
      out.write("        console.log('App context path from JSP:', window.APP_CONTEXT_PATH);\n");
      out.write("        \n");
      out.write("        // Debug: Add click handler for forgot password link\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            const forgotPasswordLink = document.getElementById('forgot-password-link');\n");
      out.write("            if (forgotPasswordLink) {\n");
      out.write("                console.log('Forgot password link found:', forgotPasswordLink);\n");
      out.write("                console.log('Link href:', forgotPasswordLink.href);\n");
      out.write("                \n");
      out.write("                // Add click event listener to debug\n");
      out.write("                forgotPasswordLink.addEventListener('click', function(e) {\n");
      out.write("                    console.log('🔗 Forgot password link clicked!');\n");
      out.write("                    console.log('Event:', e);\n");
      out.write("                    console.log('Target:', e.target);\n");
      out.write("                    console.log('Default prevented?', e.defaultPrevented);\n");
      out.write("                    \n");
      out.write("                    // Force navigation if something is preventing it\n");
      out.write("                    if (e.defaultPrevented) {\n");
      out.write("                        console.log('⚠️ Default prevented! Forcing navigation...');\n");
      out.write("                        window.location.href = this.href;\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("                \n");
      out.write("                // Test click programmatically\n");
      out.write("                setTimeout(() => {\n");
      out.write("                    console.log('Testing programmatic click...');\n");
      out.write("                    console.log('Link is:', forgotPasswordLink);\n");
      out.write("                    console.log('Link href is:', forgotPasswordLink.href);\n");
      out.write("                }, 2000);\n");
      out.write("                \n");
      out.write("            } else {\n");
      out.write("                console.error('❌ Forgot password link not found!');\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
