/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2025-06-19 00:37:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class product_002ddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Tất cả sản phẩm - 43 Gundam Hobby</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/category-popup.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-darkmode.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-bg-orange.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/navbar-menu-white.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .product-card:hover { box-shadow: 0 4px 24px rgba(0,0,0,0.12); transform: translateY(-2px); }\r\n");
      out.write("        .product-img { object-fit: cover; height: 220px; }\r\n");
      out.write("        .filter-title { font-weight: 600; font-size: 1.1rem; margin-top: 1.5rem; }\r\n");
      out.write("        .breadcrumb { background: none; }\r\n");
      out.write("        .price { color: #E55A00; font-weight: bold; font-size: 1.1rem; }\r\n");
      out.write("        .old-price { text-decoration: line-through; color: #888; font-size: 0.95em; }\r\n");
      out.write("        .discount-badge { background: #E55A00; color: #fff; font-size: 0.85em; border-radius: 6px; padding: 2px 8px; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"bg-white shadow-sm sticky-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center py-3\">\r\n");
      out.write("                <div class=\"col-lg-2 col-md-3\">\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" alt=\"43 Gundam Logo\" class=\"logo-img\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 col-md-5\">\r\n");
      out.write("                    <div class=\"search-container\">\r\n");
      out.write("                        <form class=\"search-form\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control search-input\" placeholder=\"Tìm kiếm sản phẩm...\">\r\n");
      out.write("                                <button class=\"btn btn-search\" type=\"submit\">\r\n");
      out.write("                                    <i class=\"fas fa-search\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-4\">\r\n");
      out.write("                    <div class=\"header-actions d-flex justify-content-end align-items-center\">\r\n");
      out.write("                        <div class=\"account-menu me-3\">\r\n");
      out.write("                            <div class=\"dropdown\">\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-outline-primary dropdown-toggle\" \r\n");
      out.write("                                   id=\"accountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                    <i class=\"fas fa-user me-1\"></i>\r\n");
      out.write("                                    <span>Tài khoản</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                                    <li id=\"guestLoginOption\"><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\">\r\n");
      out.write("                                        <i class=\"fas fa-sign-in-alt me-2\"></i>Đăng nhập\r\n");
      out.write("                                    </a></li>\r\n");
      out.write("                                    <li id=\"userMenu\" style=\"display:none;\">\r\n");
      out.write("                                        <span class=\"dropdown-item disabled\"><i class=\"fas fa-user me-2\"></i>Xin chào, <span id=\"userName\">User</span></span>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li id=\"userAccountOption\" style=\"display:none;\"><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/profile.jsp\">\r\n");
      out.write("                                        <i class=\"fas fa-id-card me-2\"></i>Thông tin tài khoản\r\n");
      out.write("                                    </a></li>\r\n");
      out.write("                                    <li id=\"userOrdersOption\" style=\"display:none;\"><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/profile.jsp\" onclick=\"document.getElementById('profileOrdersTab').click();return false;\">\r\n");
      out.write("                                        <i class=\"fas fa-box me-2\"></i>Đơn hàng của bạn\r\n");
      out.write("                                    </a></li>\r\n");
      out.write("                                    <li id=\"userDivider\" style=\"display:none;\"><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                                    <li id=\"userLogoutOption\" style=\"display:none;\"><a class=\"dropdown-item text-danger\" href=\"#\" onclick=\"userLogout()\">\r\n");
      out.write("                                        <i class=\"fas fa-sign-out-alt me-2\"></i>Đăng xuất\r\n");
      out.write("                                    </a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">\r\n");
      out.write("                                        <i class=\"fas fa-user-plus me-2\"></i>Đăng ký\r\n");
      out.write("                                    </a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cart-btn\">\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-cart me-1\"></i>\r\n");
      out.write("                                <span class=\"cart-count\">0</span>\r\n");
      out.write("                                <span class=\"d-none d-lg-inline ms-1\">Giỏ hàng</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- Navigation Bar -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-white shadow-sm sticky-top py-0 position-relative\">\r\n");
      out.write("        <div class=\"container position-relative\">\r\n");
      out.write("            <!-- Nút danh mục sản phẩm -->\r\n");
      out.write("            <div class=\"d-none d-lg-block position-relative\">\r\n");
      out.write("                <button class=\"btn btn-outline-primary fw-bold px-4 py-2 me-3\" id=\"categoryBtn\" type=\"button\">\r\n");
      out.write("                    <i class=\"fas fa-bars me-2\"></i> DANH MỤC SẢN PHẨM\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"category-popup shadow\" id=\"categoryPopup\">\r\n");
      out.write("                    <div class=\"category-item\">Gundam Bandai</div>\r\n");
      out.write("                    <div class=\"category-item\">Mô hình Trung</div>\r\n");
      out.write("                    <div class=\"category-item\">Metal Build - Diecast</div>\r\n");
      out.write("                    <div class=\"category-item\">Dụng cụ - Tool</div>\r\n");
      out.write("                    <div class=\"category-item\">Phụ kiện - Base</div>\r\n");
      out.write("                    <div class=\"category-item\">Mô hình Dragon Ball</div>\r\n");
      out.write("                    <div class=\"category-item\">Sơn - Decal</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Menu -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"mainNavbar\">\r\n");
      out.write("                <ul class=\"navbar-nav mx-auto mb-2 mb-lg-0\">\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link fw-bold\" href=\"");
      out.print(request.getContextPath());
      out.write("/all-products.jsp\">Tất cả sản phẩm</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link fw-bold\" href=\"#\">HÀNG MỚI VỀ</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link fw-bold\" href=\"#\">HÀNG PRE-ORDER</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle fw-bold\" href=\"#\" id=\"phukienDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            PHỤ KIỆN & MÔ HÌNH\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"phukienDropdown\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Dụng cụ - Tool</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Phụ kiện - Base</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Mô hình Dragon Ball</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle fw-bold\" href=\"#\" id=\"bandaiDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            BANDAI\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\" aria-labelledby=\"bandaiDropdown\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">High Grade (HG)</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Master Grade (MG)</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Real Grade (RG)</a></li>\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"#\">Perfect Grade (PG)</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Hero Banner -->\r\n");
      out.write("    <section class=\"hero-banner py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-9\">\r\n");
      out.write("                    <div id=\"heroCarousel\" class=\"carousel slide hero-carousel\" data-bs-ride=\"carousel\">\r\n");
      out.write("                        <div class=\"carousel-indicators\">\r\n");
      out.write("                            <button type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide-to=\"0\" class=\"active\"></button>\r\n");
      out.write("                            <button type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide-to=\"1\"></button>\r\n");
      out.write("                            <button type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide-to=\"2\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-inner\">\r\n");
      out.write("                            <div class=\"carousel-item active\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/Banner1.jpg\" class=\"d-block w-100\" alt=\"Banner 1\" \r\n");
      out.write("                                     onerror=\"this.src='https://via.placeholder.com/800x400/ff6600/ffffff?text=GUNPLA+45th+Anniversary'\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("                                    <h3 class=\"banner-title\">GUNPLA 45th Anniversary</h3>\r\n");
      out.write("                                    <p class=\"banner-subtitle\">Perfect Grade Unleashed Nu Gundam</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/Banner2.jpg\" class=\"d-block w-100\" alt=\"Banner 2\"\r\n");
      out.write("                                     onerror=\"this.src='https://via.placeholder.com/800x400/0066cc/ffffff?text=Gundam+Base+Tour'\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("                                    <h3 class=\"banner-title\">The Gundam Base World Tour 2025</h3>\r\n");
      out.write("                                    <p class=\"banner-subtitle\">Khám phá bộ sưu tập mới nhất từ Bandai</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"carousel-item\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/sale.png\" class=\"d-block w-100\" alt=\"Banner 3\"\r\n");
      out.write("                                     onerror=\"this.src='https://via.placeholder.com/800x400/cc0066/ffffff?text=Special+Sale'\">\r\n");
      out.write("                                <div class=\"carousel-caption\">\r\n");
      out.write("                                    <h3 class=\"banner-title\">Special Sale Event</h3>\r\n");
      out.write("                                    <p class=\"banner-subtitle\">Giảm giá lên đến 50% cho các sản phẩm chọn lọc</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("                            <span class=\"carousel-control-prev-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#heroCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("                            <span class=\"carousel-control-next-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3\">\r\n");
      out.write("                    <div class=\"side-banners\">\r\n");
      out.write("                        <div class=\"side-banner mb-3\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/sale.png\" class=\"img-fluid rounded\" alt=\"Sale Banner\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"side-banner\">\r\n");
      out.write("                            <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/New.jpg\" class=\"img-fluid rounded\" alt=\"New Arrivals\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Main Content All Products -->\r\n");
      out.write("    <!-- Main Content: Chi tiết sản phẩm -->\r\n");
      out.write("    <main class=\"container py-4\">\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <!-- Hình ảnh sản phẩm -->\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <div class=\"product-gallery mb-3\">\r\n");
      out.write("                    <img src=\"img/coll_1.jpg\" alt=\"Dragon Heart 1/12 Middel and Dorne Model Kit\" class=\"w-100 mb-2 shadow-sm\">\r\n");
      out.write("                    <div class=\"d-flex gap-2\">\r\n");
      out.write("                        <img src=\"img/coll_2.jpg\" alt=\"thumb1\" style=\"width: 80px; height: 80px; object-fit: cover;\">\r\n");
      out.write("                        <img src=\"img/coll_3.jpg\" alt=\"thumb2\" style=\"width: 80px; height: 80px; object-fit: cover;\">\r\n");
      out.write("                        <img src=\"img/coll_4.jpg\" alt=\"thumb3\" style=\"width: 80px; height: 80px; object-fit: cover;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Thông tin sản phẩm -->\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <h1 class=\"product-title mb-2\">[HÀNG ĐẶT TRƯỚC] MÔ HÌNH LẮP RÁP DRAGON HEART 1/12 Middel and Dorne Model Kit</h1>\r\n");
      out.write("                <div class=\"mb-2\">\r\n");
      out.write("                    <span class=\"product-price\">1.200.000₫</span>\r\n");
      out.write("                    <span class=\"old-price ms-2\">1.500.000₫</span>\r\n");
      out.write("                    <span class=\"discount-badge ms-2\">-20%</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <span class=\"badge bg-success\">Còn hàng</span>\r\n");
      out.write("                    <span class=\"badge bg-warning text-dark\">Hàng đặt trước</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <button class=\"btn btn-buy btn-lg px-4\"><i class=\"fas fa-cart-plus me-2\"></i>Thêm vào giỏ hàng</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <table class=\"table table-borderless product-info-table mb-0\">\r\n");
      out.write("                        <tr><td>Thương hiệu:</td><td>Dragon Heart</td></tr>\r\n");
      out.write("                        <tr><td>Tỉ lệ:</td><td>1/12</td></tr>\r\n");
      out.write("                        <tr><td>Chất liệu:</td><td>Nhựa cao cấp</td></tr>\r\n");
      out.write("                        <tr><td>Phân loại:</td><td>Model Kit</td></tr>\r\n");
      out.write("                        <tr><td>Tình trạng:</td><td>Đặt trước</td></tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Tabs mô tả, đánh giá -->\r\n");
      out.write("        <div class=\"row mt-4\">\r\n");
      out.write("            <div class=\"col-lg-8\">\r\n");
      out.write("                <ul class=\"nav nav-tabs mb-3\" id=\"productTab\" role=\"tablist\">\r\n");
      out.write("                    <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                        <button class=\"nav-link active\" id=\"desc-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#desc\" type=\"button\" role=\"tab\">Mô tả sản phẩm</button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                        <button class=\"nav-link\" id=\"review-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#review\" type=\"button\" role=\"tab\">Đánh giá</button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"tab-content p-3 border rounded-bottom bg-white\" id=\"productTabContent\">\r\n");
      out.write("                    <div class=\"tab-pane fade show active product-desc\" id=\"desc\" role=\"tabpanel\">\r\n");
      out.write("                        <p>Mô hình lắp ráp DRAGON HEART 1/12 Middel and Dorne Model Kit là sản phẩm cao cấp với thiết kế chi tiết, chất liệu nhựa bền đẹp, phù hợp cho cả người mới và người sưu tầm chuyên nghiệp.</p>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>Kích thước hoàn thiện: ~15cm</li>\r\n");
      out.write("                            <li>Đầy đủ phụ kiện, decal dán</li>\r\n");
      out.write("                            <li>Đóng gói hộp màu chính hãng</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <p>Lưu ý: Sản phẩm là mô hình lắp ráp, chưa bao gồm keo dán và màu sơn.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tab-pane fade\" id=\"review\" role=\"tabpanel\">\r\n");
      out.write("                        <p>Chưa có đánh giá nào cho sản phẩm này.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4\">\r\n");
      out.write("                <div class=\"card shadow-sm mb-3\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"mb-3\">Chính sách & Hỗ trợ</h5>\r\n");
      out.write("                        <ul class=\"list-unstyled mb-0\">\r\n");
      out.write("                            <li><i class=\"fas fa-shipping-fast me-2 text-success\"></i>Giao hàng toàn quốc</li>\r\n");
      out.write("                            <li><i class=\"fas fa-undo me-2 text-primary\"></i>Đổi trả trong 7 ngày</li>\r\n");
      out.write("                            <li><i class=\"fas fa-phone me-2 text-warning\"></i>Hotline: 0349 999 943</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card shadow-sm\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <h5 class=\"mb-3\">Sản phẩm liên quan</h5>\r\n");
      out.write("                        <div class=\"d-flex mb-2 align-items-center\">\r\n");
      out.write("                            <img src=\"img/coll_2.jpg\" alt=\"sp1\" style=\"width:48px;height:48px;object-fit:cover;border-radius:6px;\">\r\n");
      out.write("                            <div class=\"ms-2\">\r\n");
      out.write("                                <div style=\"font-size:1em;\">Gundam Barbatos</div>\r\n");
      out.write("                                <div class=\"price\">650.000₫</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex mb-2 align-items-center\">\r\n");
      out.write("                            <img src=\"img/coll_3.jpg\" alt=\"sp2\" style=\"width:48px;height:48px;object-fit:cover;border-radius:6px;\">\r\n");
      out.write("                            <div class=\"ms-2\">\r\n");
      out.write("                                <div style=\"font-size:1em;\">Gundam Exia</div>\r\n");
      out.write("                                <div class=\"price\">1.200.000₫</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <footer class=\"bg-dark text-white\">\r\n");
      out.write("        <div class=\"footer-top py-5\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h5 class=\"footer-title\">43 Gundam Hobby</h5>\r\n");
      out.write("                            <p class=\"footer-desc\">Chuyên cung cấp mô hình Gundam chính hãng với giá tốt nhất. Uy tín - Chất lượng - Dịch vụ tận tâm.</p>\r\n");
      out.write("                            <div class=\"store-info\">\r\n");
      out.write("                                <div class=\"info-item mb-2\">\r\n");
      out.write("                                    <i class=\"fas fa-map-marker-alt me-2\"></i>\r\n");
      out.write("                                    <span>59 Lê Đình Diên, Cẩm Lệ, Đà Nẵng</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info-item mb-2\">\r\n");
      out.write("                                    <i class=\"fas fa-phone me-2\"></i>\r\n");
      out.write("                                    <a href=\"tel:0385546145\" class=\"text-white\">0385546145 (8h-20h)</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info-item\">\r\n");
      out.write("                                    <i class=\"fas fa-envelope me-2\"></i>\r\n");
      out.write("                                    <a href=\"mailto:43gundamhobby@gmail.com\" class=\"text-white\">43gundamhobby@gmail.com</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Sản phẩm</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Gundam Bandai</a></li>\r\n");
      out.write("                                <li><a href=\"#\">High Grade (HG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Master Grade (MG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Real Grade (RG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Perfect Grade (PG)</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Metal Build</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Dịch vụ</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Hàng Pre-Order</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Dụng cụ & Phụ kiện</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Hướng dẫn lắp ráp</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Sơn & Trang trí</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Bảo hành sản phẩm</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Chính sách</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Chính sách bảo mật</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Chính sách thanh toán</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Chính sách vận chuyển</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Chính sách đổi trả</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Quy định sử dụng</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-2 col-md-6 mb-4\">\r\n");
      out.write("                        <div class=\"footer-section\">\r\n");
      out.write("                            <h6 class=\"footer-title\">Hỗ trợ</h6>\r\n");
      out.write("                            <ul class=\"footer-links\">\r\n");
      out.write("                                <li><a href=\"#\">Liên hệ</a></li>\r\n");
      out.write("                                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Hướng dẫn đặt hàng</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Tra cứu đơn hàng</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Hỗ trợ kỹ thuật</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-social py-4 bg-darker\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <h6 class=\"social-title mb-3\">Theo dõi chúng tôi</h6>\r\n");
      out.write("                        <div class=\"social-links\">\r\n");
      out.write("                            <a href=\"#\" class=\"social-link facebook\">\r\n");
      out.write("                                <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                                <span>Facebook</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-link youtube\">\r\n");
      out.write("                                <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("                                <span>Youtube</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-link tiktok\">\r\n");
      out.write("                                <i class=\"fab fa-tiktok\"></i>\r\n");
      out.write("                                <span>TikTok</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-link instagram\">\r\n");
      out.write("                                <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                                <span>Instagram</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <div class=\"newsletter\">\r\n");
      out.write("                            <h6 class=\"newsletter-title mb-3\">Đăng ký nhận tin</h6>\r\n");
      out.write("                            <form class=\"newsletter-form\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"email\" class=\"form-control\" placeholder=\"Nhập email của bạn...\">\r\n");
      out.write("                                    <button class=\"btn btn-primary\" type=\"submit\">\r\n");
      out.write("                                        <i class=\"fas fa-paper-plane\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-bottom py-3 bg-darker border-top border-secondary\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-6\">\r\n");
      out.write("                        <p class=\"copyright mb-0\">&copy; 2025 43 Gundam Hobby. All rights reserved.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                        <div class=\"payment-methods\">\r\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=VISA\" alt=\"Visa\" class=\"payment-icon\">\r\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=MC\" alt=\"Mastercard\" class=\"payment-icon\">\r\n");
      out.write("                            <img src=\"https://via.placeholder.com/40x25/cccccc/666666?text=COD\" alt=\"COD\" class=\"payment-icon\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- Back to Top Button -->\r\n");
      out.write("    <button class=\"back-to-top\" id=\"backToTop\">\r\n");
      out.write("        <i class=\"fas fa-chevron-up\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("    // Hiện/ẩn popup danh mục sản phẩm\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        var btn = document.getElementById('categoryBtn');\r\n");
      out.write("        var popup = document.getElementById('categoryPopup');\r\n");
      out.write("        if (btn && popup) {\r\n");
      out.write("            btn.addEventListener('mouseenter', function() {\r\n");
      out.write("                popup.classList.add('show');\r\n");
      out.write("            });\r\n");
      out.write("            btn.addEventListener('mouseleave', function() {\r\n");
      out.write("                setTimeout(function(){\r\n");
      out.write("                    if (!popup.matches(':hover')) popup.classList.remove('show');\r\n");
      out.write("                }, 100);\r\n");
      out.write("            });\r\n");
      out.write("            popup.addEventListener('mouseenter', function() {\r\n");
      out.write("                popup.classList.add('show');\r\n");
      out.write("            });\r\n");
      out.write("            popup.addEventListener('mouseleave', function() {\r\n");
      out.write("                popup.classList.remove('show');\r\n");
      out.write("            });\r\n");
      out.write("            // Mobile: click để toggle\r\n");
      out.write("            btn.addEventListener('click', function(e) {\r\n");
      out.write("                if (window.innerWidth < 992) {\r\n");
      out.write("                    popup.classList.toggle('show');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            // Click ngoài để ẩn\r\n");
      out.write("            document.addEventListener('click', function(e) {\r\n");
      out.write("                if (!btn.contains(e.target) && !popup.contains(e.target)) {\r\n");
      out.write("                    popup.classList.remove('show');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
