/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2025-07-10 11:56:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Thông tin khách hàng - 43 Gundam Hobby</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/hamburger-menu.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"profile-body\">    <header class=\"bg-white shadow-sm sticky-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center py-3\">\r\n");
      out.write("                <!-- Logo Section with Hamburger Menu -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6\">\r\n");
      out.write("                    <div class=\"header-logo-section\">\r\n");
      out.write("                        <!-- Hamburger Menu (Mobile) -->\r\n");
      out.write("                        <button class=\"hamburger-menu\" id=\"hamburgerBtn\" aria-label=\"Menu\">\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"logo\">\r\n");
      out.write("                            <a href=\"");
      out.print(request.getContextPath());
      out.write("/\">\r\n");
      out.write("                                <img src=\"");
      out.print(request.getContextPath());
      out.write("/img/logo.png\" alt=\"43 Gundam Logo\" class=\"logo-img\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Search Section -->\r\n");
      out.write("                <div class=\"col-lg-6 col-md-4 col-12 order-lg-2 order-md-2 order-3\">\r\n");
      out.write("                    <div class=\"header-center-section\">\r\n");
      out.write("                        <div class=\"search-container w-100\">\r\n");
      out.write("                            <form class=\"search-form\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control search-input\" placeholder=\"Tìm kiếm sản phẩm...\">\r\n");
      out.write("                                    <button class=\"btn btn-search\" type=\"submit\">\r\n");
      out.write("                                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Actions Section -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 order-lg-3 order-md-3 order-2\">\r\n");
      out.write("                    <div class=\"header-actions-section\">\r\n");
      out.write("                        <div class=\"account-menu me-3\">\r\n");
      out.write("                            ");

                                Boolean isLoggedIn = (Boolean) session.getAttribute("isLoggedIn");
                                String userName = (String) session.getAttribute("userName");
                                String userPicture = (String) session.getAttribute("userPicture");
                                String loginType = (String) session.getAttribute("loginType");
                                
                                if (isLoggedIn != null && isLoggedIn) {
                            
      out.write("<!-- User logged in -->\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-toggle text-decoration-none d-flex align-items-center\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                        ");
 if (userPicture != null && !userPicture.isEmpty()) { 
      out.write("<img src=\"");
      out.print( userPicture );
      out.write("\" alt=\"Avatar\" class=\"rounded-circle me-2 avatar-32\">\r\n");
      out.write("                                        ");
 } else { 
      out.write("<i class=\"fas fa-user-circle me-2 user-icon-32\"></i>\r\n");
      out.write("                                        ");
 } 
      out.write("<span class=\"text-dark d-none d-md-inline\">Xin chào, ");
      out.print( userName != null ? userName : "User" );
      out.write("</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end z-index-1050\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/profile.jsp\"><i class=\"fas fa-user me-2\"></i>Hồ sơ khách hàng</a></li>\r\n");
      out.write("                                        <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item text-danger\" href=\"#\" onclick=\"logoutUser()\"><i class=\"fas fa-sign-out-alt me-2\"></i>Đăng xuất</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");

                                } else {
                            
      out.write("<!-- User not logged in -->\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-outline-primary dropdown-toggle\" \r\n");
      out.write("                                       id=\"accountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                        <i class=\"fas fa-user me-1\"></i>\r\n");
      out.write("                                        <span class=\"d-none d-md-inline\">Tài khoản</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-sign-in-alt me-2\"></i>Đăng nhập\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-user-plus me-2\"></i>Đăng ký\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            ");

                                }
                            
      out.write("</div>\r\n");
      out.write("                        <div class=\"cart-btn\">\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-cart me-1\"></i>\r\n");
      out.write("                                <span class=\"cart-count\">0</span>\r\n");
      out.write("                                <span class=\"d-none d-lg-inline ms-1\">Giỏ hàng</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Mobile Sidebar Navigation -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/mobile-sidebar.jsp", out, false);
      out.write("<main class=\"container my-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <div class=\"profile-sidebar\">                    <div class=\"text-center mb-4\">\r\n");
      out.write("                        <img id=\"profileUserAvatar\" src=\"/img/default-avatar.png\" alt=\"Avatar\" class=\"rounded-circle mb-2 avatar-80\">\r\n");
      out.write("                        <h5 id=\"profileUserName\">Đang tải...</h5>\r\n");
      out.write("                        <small id=\"profileUserEmail\" class=\"text-muted\">Đang tải...</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <nav class=\"nav flex-column\">\r\n");
      out.write("                        <a class=\"nav-link active\" href=\"#\" id=\"profileInfoTab\"><i class=\"fas fa-user me-2\"></i>Thông tin tài khoản</a>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\" id=\"profileOrdersTab\"><i class=\"fas fa-box me-2\"></i>Đơn hàng của bạn</a>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\" id=\"profilePasswordTab\"><i class=\"fas fa-key me-2\"></i>Đổi mật khẩu</a>\r\n");
      out.write("                        <a class=\"nav-link\" href=\"#\" id=\"profileAddressTab\"><i class=\"fas fa-map-marker-alt me-2\"></i>Sổ địa chỉ <span class=\"badge bg-secondary ms-1\">0</span></a>\r\n");
      out.write("                        <a class=\"nav-link text-danger\" href=\"#\" id=\"profileLogoutBtn\"><i class=\"fas fa-sign-out-alt me-2\"></i>Đăng xuất</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-9\">                <div class=\"profile-content\" id=\"profileContent\">\r\n");
      out.write("                    <!-- Nội dung từng tab sẽ được hiển thị ở đây -->\r\n");
      out.write("                    <div id=\"profileInfoContent\">\r\n");
      out.write("                        <h4><i class=\"fas fa-user-circle me-2\"></i>Thông tin tài khoản</h4>\r\n");
      out.write("                        <div class=\"row mt-4\">\r\n");
      out.write("                            <div class=\"col-md-8\">\r\n");
      out.write("                                <div class=\"info-section\">\r\n");
      out.write("                                    <h6 class=\"text-muted mb-3\">Thông tin cá nhân</h6>\r\n");
      out.write("                                    <div class=\"row mb-3\">\r\n");
      out.write("                                        <div class=\"col-sm-4\"><strong>Họ tên:</strong></div>\r\n");
      out.write("                                        <div class=\"col-sm-8\" id=\"displayUserName\">Đang tải...</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row mb-3\">\r\n");
      out.write("                                        <div class=\"col-sm-4\"><strong>Email:</strong></div>\r\n");
      out.write("                                        <div class=\"col-sm-8\" id=\"displayUserEmail\">Đang tải...</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row mb-3\">\r\n");
      out.write("                                        <div class=\"col-sm-4\"><strong>Vai trò:</strong></div>\r\n");
      out.write("                                        <div class=\"col-sm-8\" id=\"displayUserRole\">Đang tải...</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row mb-3\">\r\n");
      out.write("                                        <div class=\"col-sm-4\"><strong>Đăng nhập bằng:</strong></div>\r\n");
      out.write("                                        <div class=\"col-sm-8\" id=\"displayLoginType\">Đang tải...</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4 text-center\">\r\n");
      out.write("                                <div class=\"avatar-section\">\r\n");
      out.write("                                    <img id=\"displayUserAvatar\" src=\"/img/default-avatar.png\" alt=\"Avatar\" class=\"rounded-circle mb-3 avatar-120\">\r\n");
      out.write("                                    <div class=\"mt-2\">\r\n");
      out.write("                                        <small class=\"text-muted\">Ảnh đại diện từ Google</small>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/account-dropdown.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // Hiển thị thông tin người dùng từ session\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // Lấy thông tin từ session JSP\r\n");
      out.write("            const userName = '");
      out.print( session.getAttribute("userName") != null ? session.getAttribute("userName") : "" );
      out.write("';\r\n");
      out.write("            const userEmail = '");
      out.print( session.getAttribute("userEmail") != null ? session.getAttribute("userEmail") : "" );
      out.write("';\r\n");
      out.write("            const userPicture = '");
      out.print( session.getAttribute("userPicture") != null ? session.getAttribute("userPicture") : "" );
      out.write("';\r\n");
      out.write("            const userRole = '");
      out.print( session.getAttribute("userRole") != null ? session.getAttribute("userRole") : "CUSTOMER" );
      out.write("';\r\n");
      out.write("            const loginType = '");
      out.print( session.getAttribute("loginType") != null ? session.getAttribute("loginType") : "local" );
      out.write("';\r\n");
      out.write("            \r\n");
      out.write("            // Cập nhật thông tin trong sidebar\r\n");
      out.write("            if (userName && userName !== 'null' && userName !== '') {\r\n");
      out.write("                document.getElementById('profileUserName').textContent = 'Xin chào, ' + userName;\r\n");
      out.write("                document.getElementById('displayUserName').textContent = userName;\r\n");
      out.write("            } else {\r\n");
      out.write("                document.getElementById('profileUserName').textContent = 'Chưa đăng nhập';\r\n");
      out.write("                document.getElementById('displayUserName').textContent = 'Chưa có thông tin';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if (userEmail && userEmail !== 'null' && userEmail !== '') {\r\n");
      out.write("                document.getElementById('profileUserEmail').textContent = userEmail;\r\n");
      out.write("                document.getElementById('displayUserEmail').textContent = userEmail;\r\n");
      out.write("            } else {\r\n");
      out.write("                document.getElementById('profileUserEmail').textContent = 'Chưa có email';\r\n");
      out.write("                document.getElementById('displayUserEmail').textContent = 'Chưa có thông tin';\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Cập nhật avatar\r\n");
      out.write("            if (userPicture && userPicture !== 'null' && userPicture !== '') {\r\n");
      out.write("                document.getElementById('profileUserAvatar').src = userPicture;\r\n");
      out.write("                document.getElementById('displayUserAvatar').src = userPicture;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Cập nhật role\r\n");
      out.write("            let roleText = userRole;\r\n");
      out.write("            if (userRole === 'CUSTOMER') roleText = 'Khách hàng';\r\n");
      out.write("            else if (userRole === 'ADMIN') roleText = 'Quản trị viên';\r\n");
      out.write("            else if (userRole === 'STAFF') roleText = 'Nhân viên';\r\n");
      out.write("            document.getElementById('displayUserRole').textContent = roleText;\r\n");
      out.write("            \r\n");
      out.write("            // Cập nhật login type\r\n");
      out.write("            let loginTypeText = loginType;\r\n");
      out.write("            if (loginType === 'google') loginTypeText = 'Google OAuth';\r\n");
      out.write("            else if (loginType === 'local') loginTypeText = 'Tài khoản nội bộ';\r\n");
      out.write("            document.getElementById('displayLoginType').textContent = loginTypeText;\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        // Xử lý tab switching\r\n");
      out.write("        document.getElementById('profileInfoTab').onclick = function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            // Remove active class from all tabs\r\n");
      out.write("            document.querySelectorAll('.nav-link').forEach(link => link.classList.remove('active'));\r\n");
      out.write("            // Add active class to clicked tab\r\n");
      out.write("            this.classList.add('active');\r\n");
      out.write("            \r\n");
      out.write("            // Show profile info content (đã có sẵn)\r\n");
      out.write("            const profileContent = document.getElementById('profileContent');\r\n");
      out.write("            profileContent.innerHTML = document.getElementById('profileInfoContent').outerHTML;\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById('profileOrdersTab').onclick = function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            document.querySelectorAll('.nav-link').forEach(link => link.classList.remove('active'));\r\n");
      out.write("            this.classList.add('active');\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById('profileContent').innerHTML = `\r\n");
      out.write("                <h4><i class=\"fas fa-box me-2\"></i>Đơn hàng của bạn</h4>\r\n");
      out.write("                <div id=\"order-history-list\" class=\"mt-4\">\r\n");
      out.write("                    <div class=\"text-muted\">Đang tải dữ liệu...</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Modal Gửi Khiếu Nại -->\r\n");
      out.write("                <div class=\"modal fade\" id=\"complaintModal\" tabindex=\"-1\" aria-labelledby=\"complaintModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <form id=\"complaintForm\" class=\"modal-content\">\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h5 class=\"modal-title\">Gửi khiếu nại đơn hàng</h5>\r\n");
      out.write("                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Đóng\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <input type=\"hidden\" id=\"complaintOrderId\">\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label for=\"complaintCategory\" class=\"form-label\">Danh mục (tùy chọn)</label>\r\n");
      out.write("                                    <select class=\"form-select\" id=\"complaintCategory\">\r\n");
      out.write("                                        <option value=\"\">-- Chọn danh mục khiếu nại --</option>\r\n");
      out.write("                                        <option value=\"Giao hàng trễ\">Giao hàng trễ</option>\r\n");
      out.write("                                        <option value=\"Hỏng sản phẩm\">Hỏng sản phẩm</option>\r\n");
      out.write("                                        <option value=\"Thiếu hàng\">Thiếu hàng</option>\r\n");
      out.write("                                        <option value=\"Sai hàng\">Sai hàng</option>\r\n");
      out.write("                                        <option value=\"Không đúng mô tả\">Không đúng mô tả</option>\r\n");
      out.write("                                        <option value=\"Không hoạt động\">Không hoạt động</option>\r\n");
      out.write("                                        <option value=\"Chất lượng kém\">Chất lượng kém</option>\r\n");
      out.write("                                        <option value=\"Lý do khác\">Lý do khác</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"mb-3\">\r\n");
      out.write("                                    <label for=\"complaintContent\" class=\"form-label\">Nội dung khiếu nại *</label>\r\n");
      out.write("                                    <textarea class=\"form-control\" id=\"complaintContent\" rows=\"4\" required></textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\">Gửi khiếu nại</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            `;\r\n");
      out.write("            \r\n");
      out.write("            // Load order history\r\n");
      out.write("            loadOrderHistory();\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById('profilePasswordTab').onclick = function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            document.querySelectorAll('.nav-link').forEach(link => link.classList.remove('active'));\r\n");
      out.write("            this.classList.add('active');\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById('profileContent').innerHTML = `\r\n");
      out.write("                <h4><i class=\"fas fa-key me-2\"></i>Đổi mật khẩu</h4>\r\n");
      out.write("                <div class=\"alert alert-warning mt-4\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-triangle me-2\"></i>\r\n");
      out.write("                    Chức năng này sẽ được cập nhật trong phiên bản tiếp theo.\r\n");
      out.write("                </div>\r\n");
      out.write("            `;\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById('profileAddressTab').onclick = function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            document.querySelectorAll('.nav-link').forEach(link => link.classList.remove('active'));\r\n");
      out.write("            this.classList.add('active');\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById('profileContent').innerHTML = `\r\n");
      out.write("                <h4><i class=\"fas fa-map-marker-alt me-2\"></i>Sổ địa chỉ</h4>\r\n");
      out.write("                <div class=\"alert alert-info mt-4\">\r\n");
      out.write("                    <i class=\"fas fa-info-circle me-2\"></i>\r\n");
      out.write("                    Bạn chưa có địa chỉ nào được lưu.\r\n");
      out.write("                </div>\r\n");
      out.write("            `;\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        // Xử lý đăng xuất\r\n");
      out.write("        document.getElementById('profileLogoutBtn').onclick = function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            if (confirm('Bạn có chắc chắn muốn đăng xuất?')) {\r\n");
      out.write("                logoutUser();\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        // Function đăng xuất\r\n");
      out.write("        function logoutUser() {\r\n");
      out.write("            // Gọi API logout của Spring Security OAuth2\r\n");
      out.write("            fetch('/logout', {\r\n");
      out.write("                method: 'POST',\r\n");
      out.write("                headers: {\r\n");
      out.write("                    'Content-Type': 'application/x-www-form-urlencoded',\r\n");
      out.write("                }\r\n");
      out.write("            }).then(() => {\r\n");
      out.write("                // Clear session storage\r\n");
      out.write("                sessionStorage.clear();\r\n");
      out.write("                localStorage.clear();\r\n");
      out.write("                \r\n");
      out.write("                // Redirect về trang chủ\r\n");
      out.write("                window.location.href = '/';\r\n");
      out.write("            }).catch(error => {\r\n");
      out.write("                console.error('Logout error:', error);\r\n");
      out.write("                // Fallback: redirect về trang chủ dù có lỗi\r\n");
      out.write("                window.location.href = '/';\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Functions for order history\r\n");
      out.write("        async function loadOrderHistory() {\r\n");
      out.write("            const orderHistoryList = document.getElementById('order-history-list');\r\n");
      out.write("            try {\r\n");
      out.write("                const resp = await fetch('/api/orders/history', { headers: { 'Accept': 'application/json' } });\r\n");
      out.write("                if (!resp.ok) throw new Error('Lỗi xác thực hoặc máy chủ');\r\n");
      out.write("                const data = await resp.json();\r\n");
      out.write("                if (!Array.isArray(data)) {\r\n");
      out.write("                    orderHistoryList.innerHTML = '<div class=\"text-danger\">' + (data.message || 'Không lấy được dữ liệu!') + '</div>';\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                if (data.length === 0) {\r\n");
      out.write("                    orderHistoryList.innerHTML = '<div class=\"alert alert-info\"><i class=\"fas fa-info-circle me-2\"></i>Bạn chưa có đơn hàng nào. <a href=\"/\" class=\"alert-link\">Khám phá sản phẩm ngay!</a></div>';\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                let html = '<div class=\"table-responsive\"><table class=\"table table-bordered align-middle order-table\"><thead class=\"table-light\"><tr>' +\r\n");
      out.write("                    '<th>Hình ảnh</th><th>Mã đơn</th><th>Tên sản phẩm</th><th>Ngày đặt</th><th>Trạng thái</th><th>Tổng tiền</th><th>Hành động</th></tr></thead><tbody>';\r\n");
      out.write("                data.forEach(order => {\r\n");
      out.write("                    const product = order.firstProduct || {};\r\n");
      out.write("                    html += '<tr>' +\r\n");
      out.write("                        '<td style=\"width:70px\">' + (product.image ? '<img src=\"' + product.image + '\" alt=\"Ảnh\" style=\"max-width:60px;max-height:60px;object-fit:cover;\">' : '<span class=\"text-muted\">Không có</span>') + '</td>' +\r\n");
      out.write("                        '<td class=\"fw-bold\">' + order.orderNumber + '</td>' +\r\n");
      out.write("                        '<td>' + (product.name || '<span class=\"text-muted\">Không có</span>') + '</td>' +\r\n");
      out.write("                        '<td>' + (order.orderDate ? new Date(order.orderDate).toLocaleString('vi-VN') : '') + '</td>' +\r\n");
      out.write("                        '<td>' + renderStatus(order.status) + '</td>' +\r\n");
      out.write("                        '<td class=\"text-danger fw-bold\">' + formatCurrency(order.totalAmount) + '₫</td>' +\r\n");
      out.write("                        '<td>' + renderCancelBtn(order) + '</td>' +\r\n");
      out.write("                        '</tr>';\r\n");
      out.write("                });\r\n");
      out.write("                html += '</tbody></table></div>';\r\n");
      out.write("                orderHistoryList.innerHTML = html;\r\n");
      out.write("            } catch (e) {\r\n");
      out.write("                orderHistoryList.innerHTML = '<div class=\"text-danger\">Lỗi tải dữ liệu!</div>';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function formatCurrency(num) {\r\n");
      out.write("            if (!num) return '0';\r\n");
      out.write("            return Number(num).toLocaleString('vi-VN');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function renderStatus(status) {\r\n");
      out.write("            return '<span class=\"order-status ' + status + '\">' + status + '</span>';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function renderCancelBtn(order) {\r\n");
      out.write("            if ([\"PENDING\", \"CONFIRMED\", \"PROCESSING\"].includes(order.status)) {\r\n");
      out.write("                return '<button class=\"btn btn-danger btn-sm\" onclick=\"cancelOrder(' + order.id + ', this)\"><i class=\"fas fa-trash-alt me-1\"></i>Hủy đơn</button>';\r\n");
      out.write("            } else if (order.status === \"DELIVERED\") {\r\n");
      out.write("                return '<button class=\"btn btn-warning btn-sm\" onclick=\"sendComplaint(' + order.id + ', this)\"><i class=\"fas fa-exclamation-circle me-1\"></i>Gửi khiếu nại</button>';\r\n");
      out.write("            }\r\n");
      out.write("            return '';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        window.cancelOrder = async function (orderId, btn) {\r\n");
      out.write("            if (!confirm('Bạn chắc chắn muốn xóa/hủy đơn hàng này?')) return;\r\n");
      out.write("            btn.disabled = true;\r\n");
      out.write("            btn.innerHTML = '<span class=\"spinner-border spinner-border-sm\"></span> Đang xóa...';\r\n");
      out.write("            try {\r\n");
      out.write("                const resp = await fetch('/api/orders/' + orderId + '/cancel', { method: 'POST' });\r\n");
      out.write("                const data = await resp.json();\r\n");
      out.write("                if (data.success) {\r\n");
      out.write("                    btn.closest('tr').remove();\r\n");
      out.write("                    alert('Đã xóa/hủy đơn hàng thành công!');\r\n");
      out.write("                } else {\r\n");
      out.write("                    alert(data.message || 'Không thể xóa!');\r\n");
      out.write("                    btn.disabled = false;\r\n");
      out.write("                    btn.innerHTML = '<i class=\"fas fa-trash-alt me-1\"></i>Hủy đơn';\r\n");
      out.write("                }\r\n");
      out.write("            } catch (e) {\r\n");
      out.write("                alert('Lỗi kết nối máy chủ!');\r\n");
      out.write("                btn.disabled = false;\r\n");
      out.write("                btn.innerHTML = '<i class=\"fas fa-trash-alt me-1\"></i>Hủy đơn';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        window.sendComplaint = function (orderId) {\r\n");
      out.write("            document.getElementById('complaintOrderId').value = orderId;\r\n");
      out.write("            document.getElementById('complaintForm').reset();\r\n");
      out.write("            const modal = new bootstrap.Modal(document.getElementById('complaintModal'));\r\n");
      out.write("            modal.show();\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Handle complaint form submission\r\n");
      out.write("        document.addEventListener('submit', async function(e) {\r\n");
      out.write("            if (e.target && e.target.id === 'complaintForm') {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                const orderId = document.getElementById('complaintOrderId').value;\r\n");
      out.write("                const category = document.getElementById('complaintCategory').value.trim();\r\n");
      out.write("                const content = document.getElementById('complaintContent').value.trim();\r\n");
      out.write("\r\n");
      out.write("                if (!content) {\r\n");
      out.write("                    alert('Vui lòng nhập nội dung khiếu nại!');\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                try {\r\n");
      out.write("                    const resp = await fetch('/api/complaints/create', {\r\n");
      out.write("                        method: 'POST',\r\n");
      out.write("                        headers: { 'Content-Type': 'application/json' },\r\n");
      out.write("                        body: JSON.stringify({ orderId, category, content })\r\n");
      out.write("                    });\r\n");
      out.write("                    const data = await resp.json();\r\n");
      out.write("                    if (data.success) {\r\n");
      out.write("                        alert('Gửi khiếu nại thành công!');\r\n");
      out.write("                        bootstrap.Modal.getInstance(document.getElementById('complaintModal')).hide();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(data.message || 'Gửi khiếu nại thất bại!');\r\n");
      out.write("                    }\r\n");
      out.write("                } catch (err) {\r\n");
      out.write("                    alert('Lỗi kết nối máy chủ!');\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Hamburger Menu Script -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/hamburger-menu.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
