/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-07-14 14:22:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Kết quả tìm kiếm - Gundam Hobby</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/layout-sizing.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/category-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/navbar-darkmode.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/navbar-bg-orange.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/navbar-menu-white.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/hamburger-menu.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/navbar-fix.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/account-menu-fix.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/user-avatar.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Success notification for OAuth login -->\r\n");
      out.write("    <div id=\"oauth-success-notification\" class=\"alert alert-success alert-dismissible fade oauth-notification\">\r\n");
      out.write("        <strong>🎉 Đăng nhập thành công!</strong>\r\n");
      out.write("        <p class=\"mb-0\" id=\"welcome-message\">Chào mừng bạn quay trở lại!</p>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"bg-white shadow-sm sticky-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row align-items-center py-3\">\r\n");
      out.write("                <!-- Logo Section with Hamburger Menu -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6\">\r\n");
      out.write("                    <div class=\"header-logo-section\">\r\n");
      out.write("                        <!-- Hamburger Menu (Mobile) -->\r\n");
      out.write("                        <button class=\"hamburger-menu\" id=\"hamburgerBtn\" aria-label=\"Menu\">\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                            <span class=\"line\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"logo\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\" alt=\"43 Gundam Logo\" class=\"logo-img\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Search Section -->\r\n");
      out.write("                <div class=\"col-lg-6 col-md-4 col-12 order-lg-2 order-md-2 order-3\">\r\n");
      out.write("                    <div class=\"header-center-section\">\r\n");
      out.write("                        <div class=\"search-container w-100\">\r\n");
      out.write("                            <form class=\"search-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search.jsp\" method=\"get\" id=\"headerSearchForm\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"text\" name=\"q\" class=\"form-control search-input\" \r\n");
      out.write("                                           placeholder=\"Tìm kiếm sản phẩm...\" id=\"headerSearchInput\" autocomplete=\"off\"\r\n");
      out.write("                                           value=\"");
      out.print( request.getParameter("q") != null ? request.getParameter("q") : "" );
      out.write("\">\r\n");
      out.write("                                    <button class=\"btn btn-search\" type=\"submit\">\r\n");
      out.write("                                        <i class=\"fas fa-search\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Autocomplete suggestions -->\r\n");
      out.write("                                <div id=\"headerSearchSuggestions\" class=\"search-suggestions\"></div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Actions Section -->\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-6 order-lg-3 order-md-3 order-2\">\r\n");
      out.write("                    <div class=\"header-actions-section\">\r\n");
      out.write("                        <div class=\"account-menu me-3\">\r\n");
      out.write("                            <!-- Unified Account Button -->\r\n");
      out.write("                            <div id=\"unified-account-menu\">\r\n");
      out.write("                                <div class=\"dropdown\">\r\n");
      out.write("                                    <!-- This button will dynamically change based on login state -->\r\n");
      out.write("                                    <a href=\"#\" class=\"btn btn-outline-primary dropdown-toggle\" \r\n");
      out.write("                                       id=\"unifiedAccountDropdown\" role=\"button\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                                        <!-- Content will be updated by JavaScript -->\r\n");
      out.write("                                        <i class=\"fas fa-user me-1\"></i>\r\n");
      out.write("                                        <span class=\"account-text d-none d-md-inline\">Tài khoản</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu dropdown-menu-end\" id=\"unifiedAccountDropdownMenu\">\r\n");
      out.write("                                        <!-- Menu items will be updated by JavaScript -->\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-sign-in-alt me-2\"></i>Đăng nhập\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register.jsp\">\r\n");
      out.write("                                            <i class=\"fas fa-user-plus me-2\"></i>Đăng ký\r\n");
      out.write("                                        </a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"cart-btn\">\r\n");
      out.write("                            <a href=\"cart.jsp\" class=\"btn btn-primary\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-cart me-1\"></i>\r\n");
      out.write("                                <span class=\"cart-count\">0</span>\r\n");
      out.write("                                <span class=\"d-none d-lg-inline ms-1\">Giỏ hàng</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"order-history-btn\">\r\n");
      out.write("                            <a href=\"order-history.jsp\" class=\"btn btn-outline-secondary\">\r\n");
      out.write("                                <i class=\"fas fa-history me-1\"></i>\r\n");
      out.write("                                <span class=\"d-none d-lg-inline\">Lịch sử giao dịch</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Mobile Sidebar Navigation -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/mobile-sidebar.jsp", out, false);
      out.write("<div class=\"container mt-4\">\r\n");
      out.write("        <h2>Kết quả tìm kiếm</h2>\r\n");
      out.write("        <p id=\"searchQueryDisplay\"></p>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Loading -->\r\n");
      out.write("        <div id=\"loadingIndicator\" class=\"text-center\">\r\n");
      out.write("            <div class=\"spinner-border\" role=\"status\">\r\n");
      out.write("                <span class=\"visually-hidden\">Đang tải...</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"mt-2\">Đang tìm kiếm sản phẩm...</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Products Grid -->\r\n");
      out.write("        <div id=\"productsContainer\" style=\"display: none;\">\r\n");
      out.write("            <div class=\"row\" id=\"productGrid\">\r\n");
      out.write("                <!-- Products will be loaded here -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- No Results -->\r\n");
      out.write("        <div id=\"noResults\" style=\"display: none;\">\r\n");
      out.write("            <div class=\"text-center\">\r\n");
      out.write("                <i class=\"fas fa-search fa-4x text-muted\"></i>\r\n");
      out.write("                <h4 class=\"mt-3\">Không tìm thấy sản phẩm nào</h4>\r\n");
      out.write("                <p>Hãy thử thay đổi từ khóa tìm kiếm</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Legacy navbar cleanup -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/legacy-navbar-cleanup.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- MD5 for authentication -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/md5.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Email to Google converter -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/email-to-google-converter.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Anti-flicker unified -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/anti-flicker-unified.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Search Autocomplete Script -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/search-autocomplete.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // Initialize when page loads\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            // Get query from URL parameter\r\n");
      out.write("            const urlParams = new URLSearchParams(window.location.search);\r\n");
      out.write("            const query = urlParams.get('q') || '';\r\n");
      out.write("            \r\n");
      out.write("            // Display query in UI\r\n");
      out.write("            const queryDisplay = document.getElementById('searchQueryDisplay');\r\n");
      out.write("            if (query) {\r\n");
      out.write("                queryDisplay.innerHTML = 'Tìm kiếm cho: \"<strong>' + escapeHtml(query) + '</strong>\"';\r\n");
      out.write("                loadProducts(query);\r\n");
      out.write("            } else {\r\n");
      out.write("                queryDisplay.innerHTML = '';\r\n");
      out.write("                hideLoading();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function loadProducts(query) {\r\n");
      out.write("            console.log('Loading products for query:', query);\r\n");
      out.write("            \r\n");
      out.write("            const apiUrl = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search/api?q=' + encodeURIComponent(query) + '&size=20';\r\n");
      out.write("            console.log('API URL:', apiUrl);\r\n");
      out.write("\r\n");
      out.write("            fetch(apiUrl)\r\n");
      out.write("                .then(response => {\r\n");
      out.write("                    console.log('Response status:', response.status);\r\n");
      out.write("                    if (!response.ok) {\r\n");
      out.write("                        throw new Error('API request failed: ' + response.status);\r\n");
      out.write("                    }\r\n");
      out.write("                    return response.json();\r\n");
      out.write("                })\r\n");
      out.write("                .then(data => {\r\n");
      out.write("                    console.log('API Response:', data);\r\n");
      out.write("                    hideLoading();\r\n");
      out.write("                    \r\n");
      out.write("                    if (data.success && data.products) {\r\n");
      out.write("                        displayProducts(data.products);\r\n");
      out.write("                    } else {\r\n");
      out.write("                        showNoResults();\r\n");
      out.write("                    }\r\n");
      out.write("                })\r\n");
      out.write("                .catch(error => {\r\n");
      out.write("                    console.error('Error loading products:', error);\r\n");
      out.write("                    hideLoading();\r\n");
      out.write("                    showError(error.message);\r\n");
      out.write("                });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function displayProducts(products) {\r\n");
      out.write("            console.log('Displaying products:', products.length);\r\n");
      out.write("            const container = document.getElementById('productGrid');\r\n");
      out.write("            const productsContainer = document.getElementById('productsContainer');\r\n");
      out.write("            \r\n");
      out.write("            if (!products || products.length === 0) {\r\n");
      out.write("                showNoResults();\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            document.getElementById('noResults').style.display = 'none';\r\n");
      out.write("            productsContainer.style.display = 'block';\r\n");
      out.write("            \r\n");
      out.write("            container.innerHTML = products.map(product => {\r\n");
      out.write("                const imageUrl = product.imageUrl || '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/placeholder.jpg';\r\n");
      out.write("                const price = formatPrice(product.price);\r\n");
      out.write("                \r\n");
      out.write("                return '<div class=\"col-md-4 col-lg-3 mb-4\">' +\r\n");
      out.write("                    '<div class=\"card h-100\">' +\r\n");
      out.write("                        '<img src=\"' + imageUrl + '\" class=\"card-img-top\" alt=\"' + (product.name || '') + '\" style=\"height: 200px; object-fit: cover;\" onerror=\"this.src=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/placeholder.jpg\\'\">' +\r\n");
      out.write("                        '<div class=\"card-body d-flex flex-column\">' +\r\n");
      out.write("                            '<h5 class=\"card-title\">' + (product.name || 'Tên sản phẩm') + '</h5>' +\r\n");
      out.write("                            '<p class=\"card-text text-danger fw-bold\">' + price + '</p>' +\r\n");
      out.write("                            '<div class=\"mt-auto\">' +\r\n");
      out.write("                                '<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product-detail.jsp?id=' + product.id + '\" class=\"btn btn-primary w-100\">' +\r\n");
      out.write("                                    '<i class=\"fas fa-eye me-2\"></i>Xem chi tiết' +\r\n");
      out.write("                                '</a>' +\r\n");
      out.write("                            '</div>' +\r\n");
      out.write("                        '</div>' +\r\n");
      out.write("                    '</div>' +\r\n");
      out.write("                '</div>';\r\n");
      out.write("            }).join('');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showNoResults() {\r\n");
      out.write("            document.getElementById('productsContainer').style.display = 'none';\r\n");
      out.write("            document.getElementById('noResults').style.display = 'block';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function showError(message) {\r\n");
      out.write("            document.getElementById('productsContainer').style.display = 'none';\r\n");
      out.write("            const noResults = document.getElementById('noResults');\r\n");
      out.write("            noResults.style.display = 'block';\r\n");
      out.write("            noResults.innerHTML = \r\n");
      out.write("                '<div class=\"text-center\">' +\r\n");
      out.write("                    '<i class=\"fas fa-exclamation-triangle fa-4x text-warning\"></i>' +\r\n");
      out.write("                    '<h4 class=\"mt-3\">Đã xảy ra lỗi</h4>' +\r\n");
      out.write("                    '<p>' + message + '</p>' +\r\n");
      out.write("                '</div>';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function hideLoading() {\r\n");
      out.write("            document.getElementById('loadingIndicator').style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function formatPrice(price) {\r\n");
      out.write("            return new Intl.NumberFormat('vi-VN', {\r\n");
      out.write("                style: 'currency',\r\n");
      out.write("                currency: 'VND'\r\n");
      out.write("            }).format(price);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function escapeHtml(text) {\r\n");
      out.write("            const div = document.createElement('div');\r\n");
      out.write("            div.textContent = text;\r\n");
      out.write("            return div.innerHTML;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .search-suggestions {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 100%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-top: none;\r\n");
      out.write("            border-radius: 0 0 5px 5px;\r\n");
      out.write("            max-height: 200px;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            display: none;\r\n");
      out.write("            box-shadow: 0 2px 5px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .suggestion-item {\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-bottom: 1px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .suggestion-item:hover {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .suggestion-item:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .search-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Avatar Utils -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/avatar-utils.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Cart Manager Script -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/cart-manager.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Unified Navbar Manager -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/unified-navbar-manager.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Google OAuth Handler -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/google-oauth-handler.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Authentication and Navbar Scripts -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-sync.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/navbar-manager.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/google-oauth-clean.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/navbar-fix.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/hamburger-menu.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Unified Navbar Debug -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/unified-navbar-debug.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Force check auth state after page load -->\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            console.log('📦 DOM ready, setting up unified navbar...');\r\n");
      out.write("            \r\n");
      out.write("            // Initialize cart count\r\n");
      out.write("            if (window.cartManager) {\r\n");
      out.write("                window.cartManager.updateCartCount();\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Immediate auth state debug\r\n");
      out.write("            console.log('🔍 Immediate Auth Check:');\r\n");
      out.write("            console.log('- currentUser:', localStorage.getItem('currentUser'));\r\n");
      out.write("            console.log('- googleUser:', localStorage.getItem('googleUser'));\r\n");
      out.write("            console.log('- userLoggedIn:', localStorage.getItem('userLoggedIn'));\r\n");
      out.write("            \r\n");
      out.write("            // Ensure unified navbar manager is initialized\r\n");
      out.write("            if (window.unifiedNavbarManager) {\r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    console.log('⚡ Manual auth state check...');\r\n");
      out.write("                    window.unifiedNavbarManager.checkAuthState();\r\n");
      out.write("                }, 100);\r\n");
      out.write("                \r\n");
      out.write("                setTimeout(() => {\r\n");
      out.write("                    console.log('🔄 Refreshing navbar...');\r\n");
      out.write("                    window.unifiedNavbarManager.refreshNavbar();\r\n");
      out.write("                }, 200);\r\n");
      out.write("            } else {\r\n");
      out.write("                console.warn('⚠️ unifiedNavbarManager not found!');\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            // Force check auth state multiple times to ensure sync\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                if (window.authSyncManager) {\r\n");
      out.write("                    window.authSyncManager.forceRefresh();\r\n");
      out.write("                }\r\n");
      out.write("            }, 300);\r\n");
      out.write("            \r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                if (window.authSyncManager) {\r\n");
      out.write("                    window.authSyncManager.forceRefresh();\r\n");
      out.write("                }\r\n");
      out.write("            }, 600);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
