/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2025-07-11 16:14:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class shippersc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"vi\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Shipper Dashboard - 43 Gundam Hobby</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/styles.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"css/staff-styles.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body class=\"staff-body\">\n");
      out.write("    <div class=\"staff-container\">\n");
      out.write("        <!-- Header -->\n");
      out.write("        <div class=\"staff-header\">\n");
      out.write("            <div class=\"row align-items-center\">\n");
      out.write("                <div class=\"col-md-6\">\n");
      out.write("                    <h1 class=\"mb-0\"><i class=\"fas fa-truck text-success me-3\"></i>Shipper Dashboard</h1>\n");
      out.write("                    <p class=\"mb-0 text-muted\">Quản lý đơn hàng giao nhận</p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-6 text-end\">\n");
      out.write("                    <div class=\"d-flex align-items-center justify-content-end\">\n");
      out.write("                        <div class=\"me-3\">\n");
      out.write("                            <span class=\"text-muted\">Xin chào,</span>\n");
      out.write("                            <strong>Shipper ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shipperName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"dropdown\">\n");
      out.write("                            <button class=\"btn btn-outline-success dropdown-toggle\" type=\"button\" data-bs-toggle=\"dropdown\">\n");
      out.write("                                <i class=\"fas fa-user-circle me-2\"></i>Tài khoản\n");
      out.write("                            </button>\n");
      out.write("                            <ul class=\"dropdown-menu\">\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\"><i class=\"fas fa-user me-2\"></i>Hồ sơ</a></li>\n");
      out.write("                                <li><hr class=\"dropdown-divider\"></li>\n");
      out.write("                                <li><a class=\"dropdown-item\" href=\"#\" onclick=\"logout()\"><i class=\"fas fa-sign-out-alt me-2\"></i>Đăng xuất</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Orders Table -->\n");
      out.write("        <div class=\"staff-card mt-4\">\n");
      out.write("            <div class=\"d-flex justify-content-between align-items-center mb-4\">\n");
      out.write("                <h5><i class=\"fas fa-list me-2 text-success\"></i>Đơn hàng cần giao</h5>\n");
      out.write("                <select id=\"order-status-filter\" class=\"form-select auto-width\" style=\"max-width:200px\">\n");
      out.write("                    <option value=\"ALL\">Tất cả</option>\n");
      out.write("                    <option value=\"PENDING\">Chờ giao</option>\n");
      out.write("                    <option value=\"SHIPPING\">Đang giao</option>\n");
      out.write("                    <option value=\"DELIVERED\">Đã giao</option>\n");
      out.write("                    <option value=\"FAILED\">Hủy giao hàng</option>\n");
      out.write("                    <option value=\"CANCELLED\" style=\"display:none\">Hủy giao hàng</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"table-responsive table-modern\">\n");
      out.write("                <table class=\"table table-hover\">\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Mã đơn hàng</th>\n");
      out.write("                            <th>Khách hàng</th>\n");
      out.write("                            <th>Địa chỉ giao</th>\n");
      out.write("                            <th>Số điện thoại</th>\n");
      out.write("                            <th>Trạng thái</th>\n");
      out.write("                            <th>Ngày giao</th>\n");
      out.write("                            <th>Thao tác</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody id=\"orders-table-body\">\n");
      out.write("                        <!-- Dữ liệu shipping sẽ được render từ js/shipper.js -->\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Modal: Cập nhật trạng thái đơn hàng -->\n");
      out.write("        <div class=\"modal fade\" id=\"updateStatusModal\" tabindex=\"-1\">\n");
      out.write("            <div class=\"modal-dialog\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <h5 class=\"modal-title\">Cập nhật trạng thái đơn hàng</h5>\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <input type=\"hidden\" id=\"update-order-id\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"new-status\" class=\"form-label\">Trạng thái mới:</label>\n");
      out.write("                            <select class=\"form-select\" id=\"new-status\">\n");
      out.write("                                <option value=\"PENDING\">Chờ giao</option>\n");
      out.write("                                <option value=\"SHIPPING\">Đang giao</option>\n");
      out.write("                                <option value=\"DELIVERED\">Đã giao</option>\n");
      out.write("                                <option value=\"FAILED\">Hủy giao hàng</option>\n");
      out.write("                                <option value=\"CANCELLED\" style=\"display:none\">Hủy giao hàng</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"note\" class=\"form-label\">Ghi chú (nếu có):</label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"note\" rows=\"2\"></textarea>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-footer\">\n");
      out.write("                        <button class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Đóng</button>\n");
      out.write("                        <button class=\"btn btn-primary\" onclick=\"updateOrderStatus()\">Lưu thay đổi</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Modal xem chi tiết đơn hàng -->\n");
      out.write("        <div class=\"modal fade\" id=\"orderDetailModal\" tabindex=\"-1\">\n");
      out.write("          <div class=\"modal-dialog modal-lg\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("              <div class=\"modal-header\">\n");
      out.write("                <h5 class=\"modal-title\">Chi tiết đơn hàng</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"modal-body\">\n");
      out.write("                <div id=\"order-detail-body\">\n");
      out.write("                  <!-- JavaScript sẽ render nội dung tại đây -->\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"modal-footer\">\n");
      out.write("                <button class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Đóng</button>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script src=\"js/shipper.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/js/auth.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("            checkPageAccess('SHIPPER');\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
